/*
 * lnbits
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateLNURLData
 */
public class CreateLNURLDataTest {
    private final CreateLNURLData model = new CreateLNURLData();

    /**
     * Model tests for CreateLNURLData
     */
    @Test
    public void testCreateLNURLData() {
        // TODO: test CreateLNURLData
    }

    /**
     * Test the property 'descriptionHash'
     */
    @Test
    public void descriptionHashTest() {
        // TODO: test descriptionHash
    }

    /**
     * Test the property 'callback'
     */
    @Test
    public void callbackTest() {
        // TODO: test callback
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

}
