/*
 * lnbits
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateExtension
 */
public class CreateExtensionTest {
    private final CreateExtension model = new CreateExtension();

    /**
     * Model tests for CreateExtension
     */
    @Test
    public void testCreateExtension() {
        // TODO: test CreateExtension
    }

    /**
     * Test the property 'extId'
     */
    @Test
    public void extIdTest() {
        // TODO: test extId
    }

    /**
     * Test the property 'archive'
     */
    @Test
    public void archiveTest() {
        // TODO: test archive
    }

    /**
     * Test the property 'sourceRepo'
     */
    @Test
    public void sourceRepoTest() {
        // TODO: test sourceRepo
    }

}
