/*
 * lnbits
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateInvoiceData
 */
public class CreateInvoiceDataTest {
    private final CreateInvoiceData model = new CreateInvoiceData();

    /**
     * Model tests for CreateInvoiceData
     */
    @Test
    public void testCreateInvoiceData() {
        // TODO: test CreateInvoiceData
    }

    /**
     * Test the property 'out'
     */
    @Test
    public void outTest() {
        // TODO: test out
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'memo'
     */
    @Test
    public void memoTest() {
        // TODO: test memo
    }

    /**
     * Test the property 'unit'
     */
    @Test
    public void unitTest() {
        // TODO: test unit
    }

    /**
     * Test the property 'descriptionHash'
     */
    @Test
    public void descriptionHashTest() {
        // TODO: test descriptionHash
    }

    /**
     * Test the property 'unhashedDescription'
     */
    @Test
    public void unhashedDescriptionTest() {
        // TODO: test unhashedDescription
    }

    /**
     * Test the property 'expiry'
     */
    @Test
    public void expiryTest() {
        // TODO: test expiry
    }

    /**
     * Test the property 'lnurlCallback'
     */
    @Test
    public void lnurlCallbackTest() {
        // TODO: test lnurlCallback
    }

    /**
     * Test the property 'lnurlBalanceCheck'
     */
    @Test
    public void lnurlBalanceCheckTest() {
        // TODO: test lnurlBalanceCheck
    }

    /**
     * Test the property 'extra'
     */
    @Test
    public void extraTest() {
        // TODO: test extra
    }

    /**
     * Test the property 'webhook'
     */
    @Test
    public void webhookTest() {
        // TODO: test webhook
    }

    /**
     * Test the property 'internal'
     */
    @Test
    public void internalTest() {
        // TODO: test internal
    }

    /**
     * Test the property 'bolt11'
     */
    @Test
    public void bolt11Test() {
        // TODO: test bolt11
    }

}
