/*
 * lnbits
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EditableSettings
 */
public class EditableSettingsTest {
    private final EditableSettings model = new EditableSettings();

    /**
     * Model tests for EditableSettings
     */
    @Test
    public void testEditableSettings() {
        // TODO: test EditableSettings
    }

    /**
     * Test the property 'lightningInvoiceExpiry'
     */
    @Test
    public void lightningInvoiceExpiryTest() {
        // TODO: test lightningInvoiceExpiry
    }

    /**
     * Test the property 'boltzNetwork'
     */
    @Test
    public void boltzNetworkTest() {
        // TODO: test boltzNetwork
    }

    /**
     * Test the property 'boltzUrl'
     */
    @Test
    public void boltzUrlTest() {
        // TODO: test boltzUrl
    }

    /**
     * Test the property 'boltzMempoolSpaceUrl'
     */
    @Test
    public void boltzMempoolSpaceUrlTest() {
        // TODO: test boltzMempoolSpaceUrl
    }

    /**
     * Test the property 'boltzMempoolSpaceUrlWs'
     */
    @Test
    public void boltzMempoolSpaceUrlWsTest() {
        // TODO: test boltzMempoolSpaceUrlWs
    }

    /**
     * Test the property 'lntipsApiEndpoint'
     */
    @Test
    public void lntipsApiEndpointTest() {
        // TODO: test lntipsApiEndpoint
    }

    /**
     * Test the property 'lntipsApiKey'
     */
    @Test
    public void lntipsApiKeyTest() {
        // TODO: test lntipsApiKey
    }

    /**
     * Test the property 'lntipsAdminKey'
     */
    @Test
    public void lntipsAdminKeyTest() {
        // TODO: test lntipsAdminKey
    }

    /**
     * Test the property 'lntipsInvoiceKey'
     */
    @Test
    public void lntipsInvoiceKeyTest() {
        // TODO: test lntipsInvoiceKey
    }

    /**
     * Test the property 'sparkUrl'
     */
    @Test
    public void sparkUrlTest() {
        // TODO: test sparkUrl
    }

    /**
     * Test the property 'sparkToken'
     */
    @Test
    public void sparkTokenTest() {
        // TODO: test sparkToken
    }

    /**
     * Test the property 'opennodeApiEndpoint'
     */
    @Test
    public void opennodeApiEndpointTest() {
        // TODO: test opennodeApiEndpoint
    }

    /**
     * Test the property 'opennodeKey'
     */
    @Test
    public void opennodeKeyTest() {
        // TODO: test opennodeKey
    }

    /**
     * Test the property 'opennodeAdminKey'
     */
    @Test
    public void opennodeAdminKeyTest() {
        // TODO: test opennodeAdminKey
    }

    /**
     * Test the property 'opennodeInvoiceKey'
     */
    @Test
    public void opennodeInvoiceKeyTest() {
        // TODO: test opennodeInvoiceKey
    }

    /**
     * Test the property 'lnpayApiEndpoint'
     */
    @Test
    public void lnpayApiEndpointTest() {
        // TODO: test lnpayApiEndpoint
    }

    /**
     * Test the property 'lnpayApiKey'
     */
    @Test
    public void lnpayApiKeyTest() {
        // TODO: test lnpayApiKey
    }

    /**
     * Test the property 'lnpayWalletKey'
     */
    @Test
    public void lnpayWalletKeyTest() {
        // TODO: test lnpayWalletKey
    }

    /**
     * Test the property 'lnpayAdminKey'
     */
    @Test
    public void lnpayAdminKeyTest() {
        // TODO: test lnpayAdminKey
    }

    /**
     * Test the property 'lndGrpcEndpoint'
     */
    @Test
    public void lndGrpcEndpointTest() {
        // TODO: test lndGrpcEndpoint
    }

    /**
     * Test the property 'lndGrpcCert'
     */
    @Test
    public void lndGrpcCertTest() {
        // TODO: test lndGrpcCert
    }

    /**
     * Test the property 'lndGrpcPort'
     */
    @Test
    public void lndGrpcPortTest() {
        // TODO: test lndGrpcPort
    }

    /**
     * Test the property 'lndGrpcAdminMacaroon'
     */
    @Test
    public void lndGrpcAdminMacaroonTest() {
        // TODO: test lndGrpcAdminMacaroon
    }

    /**
     * Test the property 'lndGrpcInvoiceMacaroon'
     */
    @Test
    public void lndGrpcInvoiceMacaroonTest() {
        // TODO: test lndGrpcInvoiceMacaroon
    }

    /**
     * Test the property 'lndGrpcMacaroon'
     */
    @Test
    public void lndGrpcMacaroonTest() {
        // TODO: test lndGrpcMacaroon
    }

    /**
     * Test the property 'lndGrpcMacaroonEncrypted'
     */
    @Test
    public void lndGrpcMacaroonEncryptedTest() {
        // TODO: test lndGrpcMacaroonEncrypted
    }

    /**
     * Test the property 'lndRestEndpoint'
     */
    @Test
    public void lndRestEndpointTest() {
        // TODO: test lndRestEndpoint
    }

    /**
     * Test the property 'lndRestCert'
     */
    @Test
    public void lndRestCertTest() {
        // TODO: test lndRestCert
    }

    /**
     * Test the property 'lndRestMacaroon'
     */
    @Test
    public void lndRestMacaroonTest() {
        // TODO: test lndRestMacaroon
    }

    /**
     * Test the property 'lndRestMacaroonEncrypted'
     */
    @Test
    public void lndRestMacaroonEncryptedTest() {
        // TODO: test lndRestMacaroonEncrypted
    }

    /**
     * Test the property 'lndCert'
     */
    @Test
    public void lndCertTest() {
        // TODO: test lndCert
    }

    /**
     * Test the property 'lndAdminMacaroon'
     */
    @Test
    public void lndAdminMacaroonTest() {
        // TODO: test lndAdminMacaroon
    }

    /**
     * Test the property 'lndInvoiceMacaroon'
     */
    @Test
    public void lndInvoiceMacaroonTest() {
        // TODO: test lndInvoiceMacaroon
    }

    /**
     * Test the property 'lndRestAdminMacaroon'
     */
    @Test
    public void lndRestAdminMacaroonTest() {
        // TODO: test lndRestAdminMacaroon
    }

    /**
     * Test the property 'lndRestInvoiceMacaroon'
     */
    @Test
    public void lndRestInvoiceMacaroonTest() {
        // TODO: test lndRestInvoiceMacaroon
    }

    /**
     * Test the property 'eclairUrl'
     */
    @Test
    public void eclairUrlTest() {
        // TODO: test eclairUrl
    }

    /**
     * Test the property 'eclairPass'
     */
    @Test
    public void eclairPassTest() {
        // TODO: test eclairPass
    }

    /**
     * Test the property 'corelightningRpc'
     */
    @Test
    public void corelightningRpcTest() {
        // TODO: test corelightningRpc
    }

    /**
     * Test the property 'clightningRpc'
     */
    @Test
    public void clightningRpcTest() {
        // TODO: test clightningRpc
    }

    /**
     * Test the property 'clicheEndpoint'
     */
    @Test
    public void clicheEndpointTest() {
        // TODO: test clicheEndpoint
    }

    /**
     * Test the property 'lnbitsEndpoint'
     */
    @Test
    public void lnbitsEndpointTest() {
        // TODO: test lnbitsEndpoint
    }

    /**
     * Test the property 'lnbitsKey'
     */
    @Test
    public void lnbitsKeyTest() {
        // TODO: test lnbitsKey
    }

    /**
     * Test the property 'lnbitsAdminKey'
     */
    @Test
    public void lnbitsAdminKeyTest() {
        // TODO: test lnbitsAdminKey
    }

    /**
     * Test the property 'lnbitsInvoiceKey'
     */
    @Test
    public void lnbitsInvoiceKeyTest() {
        // TODO: test lnbitsInvoiceKey
    }

    /**
     * Test the property 'fakeWalletSecret'
     */
    @Test
    public void fakeWalletSecretTest() {
        // TODO: test fakeWalletSecret
    }

    /**
     * Test the property 'lnbitsBackendWalletClass'
     */
    @Test
    public void lnbitsBackendWalletClassTest() {
        // TODO: test lnbitsBackendWalletClass
    }

    /**
     * Test the property 'lnbitsRateLimitNo'
     */
    @Test
    public void lnbitsRateLimitNoTest() {
        // TODO: test lnbitsRateLimitNo
    }

    /**
     * Test the property 'lnbitsRateLimitUnit'
     */
    @Test
    public void lnbitsRateLimitUnitTest() {
        // TODO: test lnbitsRateLimitUnit
    }

    /**
     * Test the property 'lnbitsAllowedIps'
     */
    @Test
    public void lnbitsAllowedIpsTest() {
        // TODO: test lnbitsAllowedIps
    }

    /**
     * Test the property 'lnbitsBlockedIps'
     */
    @Test
    public void lnbitsBlockedIpsTest() {
        // TODO: test lnbitsBlockedIps
    }

    /**
     * Test the property 'lnbitsNotifications'
     */
    @Test
    public void lnbitsNotificationsTest() {
        // TODO: test lnbitsNotifications
    }

    /**
     * Test the property 'lnbitsKillswitch'
     */
    @Test
    public void lnbitsKillswitchTest() {
        // TODO: test lnbitsKillswitch
    }

    /**
     * Test the property 'lnbitsKillswitchInterval'
     */
    @Test
    public void lnbitsKillswitchIntervalTest() {
        // TODO: test lnbitsKillswitchInterval
    }

    /**
     * Test the property 'lnbitsWatchdog'
     */
    @Test
    public void lnbitsWatchdogTest() {
        // TODO: test lnbitsWatchdog
    }

    /**
     * Test the property 'lnbitsWatchdogInterval'
     */
    @Test
    public void lnbitsWatchdogIntervalTest() {
        // TODO: test lnbitsWatchdogInterval
    }

    /**
     * Test the property 'lnbitsWatchdogDelta'
     */
    @Test
    public void lnbitsWatchdogDeltaTest() {
        // TODO: test lnbitsWatchdogDelta
    }

    /**
     * Test the property 'lnbitsStatusManifest'
     */
    @Test
    public void lnbitsStatusManifestTest() {
        // TODO: test lnbitsStatusManifest
    }

    /**
     * Test the property 'lnbitsBaseurl'
     */
    @Test
    public void lnbitsBaseurlTest() {
        // TODO: test lnbitsBaseurl
    }

    /**
     * Test the property 'lnbitsReserveFeeMin'
     */
    @Test
    public void lnbitsReserveFeeMinTest() {
        // TODO: test lnbitsReserveFeeMin
    }

    /**
     * Test the property 'lnbitsReserveFeePercent'
     */
    @Test
    public void lnbitsReserveFeePercentTest() {
        // TODO: test lnbitsReserveFeePercent
    }

    /**
     * Test the property 'lnbitsServiceFee'
     */
    @Test
    public void lnbitsServiceFeeTest() {
        // TODO: test lnbitsServiceFee
    }

    /**
     * Test the property 'lnbitsHideApi'
     */
    @Test
    public void lnbitsHideApiTest() {
        // TODO: test lnbitsHideApi
    }

    /**
     * Test the property 'lnbitsDenomination'
     */
    @Test
    public void lnbitsDenominationTest() {
        // TODO: test lnbitsDenomination
    }

    /**
     * Test the property 'lnbitsSiteTitle'
     */
    @Test
    public void lnbitsSiteTitleTest() {
        // TODO: test lnbitsSiteTitle
    }

    /**
     * Test the property 'lnbitsSiteTagline'
     */
    @Test
    public void lnbitsSiteTaglineTest() {
        // TODO: test lnbitsSiteTagline
    }

    /**
     * Test the property 'lnbitsSiteDescription'
     */
    @Test
    public void lnbitsSiteDescriptionTest() {
        // TODO: test lnbitsSiteDescription
    }

    /**
     * Test the property 'lnbitsDefaultWalletName'
     */
    @Test
    public void lnbitsDefaultWalletNameTest() {
        // TODO: test lnbitsDefaultWalletName
    }

    /**
     * Test the property 'lnbitsThemeOptions'
     */
    @Test
    public void lnbitsThemeOptionsTest() {
        // TODO: test lnbitsThemeOptions
    }

    /**
     * Test the property 'lnbitsCustomLogo'
     */
    @Test
    public void lnbitsCustomLogoTest() {
        // TODO: test lnbitsCustomLogo
    }

    /**
     * Test the property 'lnbitsAdSpaceTitle'
     */
    @Test
    public void lnbitsAdSpaceTitleTest() {
        // TODO: test lnbitsAdSpaceTitle
    }

    /**
     * Test the property 'lnbitsAdSpace'
     */
    @Test
    public void lnbitsAdSpaceTest() {
        // TODO: test lnbitsAdSpace
    }

    /**
     * Test the property 'lnbitsAdSpaceEnabled'
     */
    @Test
    public void lnbitsAdSpaceEnabledTest() {
        // TODO: test lnbitsAdSpaceEnabled
    }

    /**
     * Test the property 'lnbitsAllowedCurrencies'
     */
    @Test
    public void lnbitsAllowedCurrenciesTest() {
        // TODO: test lnbitsAllowedCurrencies
    }

    /**
     * Test the property 'lnbitsAdminExtensions'
     */
    @Test
    public void lnbitsAdminExtensionsTest() {
        // TODO: test lnbitsAdminExtensions
    }

    /**
     * Test the property 'lnbitsExtensionsManifests'
     */
    @Test
    public void lnbitsExtensionsManifestsTest() {
        // TODO: test lnbitsExtensionsManifests
    }

    /**
     * Test the property 'lnbitsAdminUsers'
     */
    @Test
    public void lnbitsAdminUsersTest() {
        // TODO: test lnbitsAdminUsers
    }

    /**
     * Test the property 'lnbitsAllowedUsers'
     */
    @Test
    public void lnbitsAllowedUsersTest() {
        // TODO: test lnbitsAllowedUsers
    }

}
