/*
 * lnbits
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Base class for settings, allowing values to be overridden by environment variables.  This is useful in production for secrets you do not wish to save in code, it plays nicely with docker(-compose), Heroku and any 12 factor app design.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-01T17:53:25.667+02:00[Europe/Vienna]")
public class EditableSettings {
  public static final String SERIALIZED_NAME_LIGHTNING_INVOICE_EXPIRY = "lightning_invoice_expiry";
  @SerializedName(SERIALIZED_NAME_LIGHTNING_INVOICE_EXPIRY)
  private Integer lightningInvoiceExpiry = 600;

  public static final String SERIALIZED_NAME_BOLTZ_NETWORK = "boltz_network";
  @SerializedName(SERIALIZED_NAME_BOLTZ_NETWORK)
  private String boltzNetwork = "main";

  public static final String SERIALIZED_NAME_BOLTZ_URL = "boltz_url";
  @SerializedName(SERIALIZED_NAME_BOLTZ_URL)
  private String boltzUrl = "https://boltz.exchange/api";

  public static final String SERIALIZED_NAME_BOLTZ_MEMPOOL_SPACE_URL = "boltz_mempool_space_url";
  @SerializedName(SERIALIZED_NAME_BOLTZ_MEMPOOL_SPACE_URL)
  private String boltzMempoolSpaceUrl = "https://mempool.space";

  public static final String SERIALIZED_NAME_BOLTZ_MEMPOOL_SPACE_URL_WS = "boltz_mempool_space_url_ws";
  @SerializedName(SERIALIZED_NAME_BOLTZ_MEMPOOL_SPACE_URL_WS)
  private String boltzMempoolSpaceUrlWs = "wss://mempool.space";

  public static final String SERIALIZED_NAME_LNTIPS_API_ENDPOINT = "lntips_api_endpoint";
  @SerializedName(SERIALIZED_NAME_LNTIPS_API_ENDPOINT)
  private String lntipsApiEndpoint;

  public static final String SERIALIZED_NAME_LNTIPS_API_KEY = "lntips_api_key";
  @SerializedName(SERIALIZED_NAME_LNTIPS_API_KEY)
  private String lntipsApiKey;

  public static final String SERIALIZED_NAME_LNTIPS_ADMIN_KEY = "lntips_admin_key";
  @SerializedName(SERIALIZED_NAME_LNTIPS_ADMIN_KEY)
  private String lntipsAdminKey;

  public static final String SERIALIZED_NAME_LNTIPS_INVOICE_KEY = "lntips_invoice_key";
  @SerializedName(SERIALIZED_NAME_LNTIPS_INVOICE_KEY)
  private String lntipsInvoiceKey;

  public static final String SERIALIZED_NAME_SPARK_URL = "spark_url";
  @SerializedName(SERIALIZED_NAME_SPARK_URL)
  private String sparkUrl;

  public static final String SERIALIZED_NAME_SPARK_TOKEN = "spark_token";
  @SerializedName(SERIALIZED_NAME_SPARK_TOKEN)
  private String sparkToken;

  public static final String SERIALIZED_NAME_OPENNODE_API_ENDPOINT = "opennode_api_endpoint";
  @SerializedName(SERIALIZED_NAME_OPENNODE_API_ENDPOINT)
  private String opennodeApiEndpoint;

  public static final String SERIALIZED_NAME_OPENNODE_KEY = "opennode_key";
  @SerializedName(SERIALIZED_NAME_OPENNODE_KEY)
  private String opennodeKey;

  public static final String SERIALIZED_NAME_OPENNODE_ADMIN_KEY = "opennode_admin_key";
  @SerializedName(SERIALIZED_NAME_OPENNODE_ADMIN_KEY)
  private String opennodeAdminKey;

  public static final String SERIALIZED_NAME_OPENNODE_INVOICE_KEY = "opennode_invoice_key";
  @SerializedName(SERIALIZED_NAME_OPENNODE_INVOICE_KEY)
  private String opennodeInvoiceKey;

  public static final String SERIALIZED_NAME_LNPAY_API_ENDPOINT = "lnpay_api_endpoint";
  @SerializedName(SERIALIZED_NAME_LNPAY_API_ENDPOINT)
  private String lnpayApiEndpoint;

  public static final String SERIALIZED_NAME_LNPAY_API_KEY = "lnpay_api_key";
  @SerializedName(SERIALIZED_NAME_LNPAY_API_KEY)
  private String lnpayApiKey;

  public static final String SERIALIZED_NAME_LNPAY_WALLET_KEY = "lnpay_wallet_key";
  @SerializedName(SERIALIZED_NAME_LNPAY_WALLET_KEY)
  private String lnpayWalletKey;

  public static final String SERIALIZED_NAME_LNPAY_ADMIN_KEY = "lnpay_admin_key";
  @SerializedName(SERIALIZED_NAME_LNPAY_ADMIN_KEY)
  private String lnpayAdminKey;

  public static final String SERIALIZED_NAME_LND_GRPC_ENDPOINT = "lnd_grpc_endpoint";
  @SerializedName(SERIALIZED_NAME_LND_GRPC_ENDPOINT)
  private String lndGrpcEndpoint;

  public static final String SERIALIZED_NAME_LND_GRPC_CERT = "lnd_grpc_cert";
  @SerializedName(SERIALIZED_NAME_LND_GRPC_CERT)
  private String lndGrpcCert;

  public static final String SERIALIZED_NAME_LND_GRPC_PORT = "lnd_grpc_port";
  @SerializedName(SERIALIZED_NAME_LND_GRPC_PORT)
  private Integer lndGrpcPort;

  public static final String SERIALIZED_NAME_LND_GRPC_ADMIN_MACAROON = "lnd_grpc_admin_macaroon";
  @SerializedName(SERIALIZED_NAME_LND_GRPC_ADMIN_MACAROON)
  private String lndGrpcAdminMacaroon;

  public static final String SERIALIZED_NAME_LND_GRPC_INVOICE_MACAROON = "lnd_grpc_invoice_macaroon";
  @SerializedName(SERIALIZED_NAME_LND_GRPC_INVOICE_MACAROON)
  private String lndGrpcInvoiceMacaroon;

  public static final String SERIALIZED_NAME_LND_GRPC_MACAROON = "lnd_grpc_macaroon";
  @SerializedName(SERIALIZED_NAME_LND_GRPC_MACAROON)
  private String lndGrpcMacaroon;

  public static final String SERIALIZED_NAME_LND_GRPC_MACAROON_ENCRYPTED = "lnd_grpc_macaroon_encrypted";
  @SerializedName(SERIALIZED_NAME_LND_GRPC_MACAROON_ENCRYPTED)
  private String lndGrpcMacaroonEncrypted;

  public static final String SERIALIZED_NAME_LND_REST_ENDPOINT = "lnd_rest_endpoint";
  @SerializedName(SERIALIZED_NAME_LND_REST_ENDPOINT)
  private String lndRestEndpoint;

  public static final String SERIALIZED_NAME_LND_REST_CERT = "lnd_rest_cert";
  @SerializedName(SERIALIZED_NAME_LND_REST_CERT)
  private String lndRestCert;

  public static final String SERIALIZED_NAME_LND_REST_MACAROON = "lnd_rest_macaroon";
  @SerializedName(SERIALIZED_NAME_LND_REST_MACAROON)
  private String lndRestMacaroon;

  public static final String SERIALIZED_NAME_LND_REST_MACAROON_ENCRYPTED = "lnd_rest_macaroon_encrypted";
  @SerializedName(SERIALIZED_NAME_LND_REST_MACAROON_ENCRYPTED)
  private String lndRestMacaroonEncrypted;

  public static final String SERIALIZED_NAME_LND_CERT = "lnd_cert";
  @SerializedName(SERIALIZED_NAME_LND_CERT)
  private String lndCert;

  public static final String SERIALIZED_NAME_LND_ADMIN_MACAROON = "lnd_admin_macaroon";
  @SerializedName(SERIALIZED_NAME_LND_ADMIN_MACAROON)
  private String lndAdminMacaroon;

  public static final String SERIALIZED_NAME_LND_INVOICE_MACAROON = "lnd_invoice_macaroon";
  @SerializedName(SERIALIZED_NAME_LND_INVOICE_MACAROON)
  private String lndInvoiceMacaroon;

  public static final String SERIALIZED_NAME_LND_REST_ADMIN_MACAROON = "lnd_rest_admin_macaroon";
  @SerializedName(SERIALIZED_NAME_LND_REST_ADMIN_MACAROON)
  private String lndRestAdminMacaroon;

  public static final String SERIALIZED_NAME_LND_REST_INVOICE_MACAROON = "lnd_rest_invoice_macaroon";
  @SerializedName(SERIALIZED_NAME_LND_REST_INVOICE_MACAROON)
  private String lndRestInvoiceMacaroon;

  public static final String SERIALIZED_NAME_ECLAIR_URL = "eclair_url";
  @SerializedName(SERIALIZED_NAME_ECLAIR_URL)
  private String eclairUrl;

  public static final String SERIALIZED_NAME_ECLAIR_PASS = "eclair_pass";
  @SerializedName(SERIALIZED_NAME_ECLAIR_PASS)
  private String eclairPass;

  public static final String SERIALIZED_NAME_CORELIGHTNING_RPC = "corelightning_rpc";
  @SerializedName(SERIALIZED_NAME_CORELIGHTNING_RPC)
  private String corelightningRpc;

  public static final String SERIALIZED_NAME_CLIGHTNING_RPC = "clightning_rpc";
  @SerializedName(SERIALIZED_NAME_CLIGHTNING_RPC)
  private String clightningRpc;

  public static final String SERIALIZED_NAME_CLICHE_ENDPOINT = "cliche_endpoint";
  @SerializedName(SERIALIZED_NAME_CLICHE_ENDPOINT)
  private String clicheEndpoint;

  public static final String SERIALIZED_NAME_LNBITS_ENDPOINT = "lnbits_endpoint";
  @SerializedName(SERIALIZED_NAME_LNBITS_ENDPOINT)
  private String lnbitsEndpoint = "https://legend.lnbits.com";

  public static final String SERIALIZED_NAME_LNBITS_KEY = "lnbits_key";
  @SerializedName(SERIALIZED_NAME_LNBITS_KEY)
  private String lnbitsKey;

  public static final String SERIALIZED_NAME_LNBITS_ADMIN_KEY = "lnbits_admin_key";
  @SerializedName(SERIALIZED_NAME_LNBITS_ADMIN_KEY)
  private String lnbitsAdminKey;

  public static final String SERIALIZED_NAME_LNBITS_INVOICE_KEY = "lnbits_invoice_key";
  @SerializedName(SERIALIZED_NAME_LNBITS_INVOICE_KEY)
  private String lnbitsInvoiceKey;

  public static final String SERIALIZED_NAME_FAKE_WALLET_SECRET = "fake_wallet_secret";
  @SerializedName(SERIALIZED_NAME_FAKE_WALLET_SECRET)
  private String fakeWalletSecret = "ToTheMoon1";

  public static final String SERIALIZED_NAME_LNBITS_BACKEND_WALLET_CLASS = "lnbits_backend_wallet_class";
  @SerializedName(SERIALIZED_NAME_LNBITS_BACKEND_WALLET_CLASS)
  private String lnbitsBackendWalletClass = "VoidWallet";

  public static final String SERIALIZED_NAME_LNBITS_RATE_LIMIT_NO = "lnbits_rate_limit_no";
  @SerializedName(SERIALIZED_NAME_LNBITS_RATE_LIMIT_NO)
  private String lnbitsRateLimitNo = "200";

  public static final String SERIALIZED_NAME_LNBITS_RATE_LIMIT_UNIT = "lnbits_rate_limit_unit";
  @SerializedName(SERIALIZED_NAME_LNBITS_RATE_LIMIT_UNIT)
  private String lnbitsRateLimitUnit = "minute";

  public static final String SERIALIZED_NAME_LNBITS_ALLOWED_IPS = "lnbits_allowed_ips";
  @SerializedName(SERIALIZED_NAME_LNBITS_ALLOWED_IPS)
  private List<String> lnbitsAllowedIps = null;

  public static final String SERIALIZED_NAME_LNBITS_BLOCKED_IPS = "lnbits_blocked_ips";
  @SerializedName(SERIALIZED_NAME_LNBITS_BLOCKED_IPS)
  private List<String> lnbitsBlockedIps = null;

  public static final String SERIALIZED_NAME_LNBITS_NOTIFICATIONS = "lnbits_notifications";
  @SerializedName(SERIALIZED_NAME_LNBITS_NOTIFICATIONS)
  private Boolean lnbitsNotifications = false;

  public static final String SERIALIZED_NAME_LNBITS_KILLSWITCH = "lnbits_killswitch";
  @SerializedName(SERIALIZED_NAME_LNBITS_KILLSWITCH)
  private Boolean lnbitsKillswitch = false;

  public static final String SERIALIZED_NAME_LNBITS_KILLSWITCH_INTERVAL = "lnbits_killswitch_interval";
  @SerializedName(SERIALIZED_NAME_LNBITS_KILLSWITCH_INTERVAL)
  private Integer lnbitsKillswitchInterval = 60;

  public static final String SERIALIZED_NAME_LNBITS_WATCHDOG = "lnbits_watchdog";
  @SerializedName(SERIALIZED_NAME_LNBITS_WATCHDOG)
  private Boolean lnbitsWatchdog = false;

  public static final String SERIALIZED_NAME_LNBITS_WATCHDOG_INTERVAL = "lnbits_watchdog_interval";
  @SerializedName(SERIALIZED_NAME_LNBITS_WATCHDOG_INTERVAL)
  private Integer lnbitsWatchdogInterval = 60;

  public static final String SERIALIZED_NAME_LNBITS_WATCHDOG_DELTA = "lnbits_watchdog_delta";
  @SerializedName(SERIALIZED_NAME_LNBITS_WATCHDOG_DELTA)
  private Integer lnbitsWatchdogDelta = 1000000;

  public static final String SERIALIZED_NAME_LNBITS_STATUS_MANIFEST = "lnbits_status_manifest";
  @SerializedName(SERIALIZED_NAME_LNBITS_STATUS_MANIFEST)
  private String lnbitsStatusManifest = "https://raw.githubusercontent.com/lnbits/lnbits-status/main/manifest.json";

  public static final String SERIALIZED_NAME_LNBITS_BASEURL = "lnbits_baseurl";
  @SerializedName(SERIALIZED_NAME_LNBITS_BASEURL)
  private String lnbitsBaseurl = "http://127.0.0.1:5000/";

  public static final String SERIALIZED_NAME_LNBITS_RESERVE_FEE_MIN = "lnbits_reserve_fee_min";
  @SerializedName(SERIALIZED_NAME_LNBITS_RESERVE_FEE_MIN)
  private Integer lnbitsReserveFeeMin = 2000;

  public static final String SERIALIZED_NAME_LNBITS_RESERVE_FEE_PERCENT = "lnbits_reserve_fee_percent";
  @SerializedName(SERIALIZED_NAME_LNBITS_RESERVE_FEE_PERCENT)
  private BigDecimal lnbitsReserveFeePercent = new BigDecimal("1.0");

  public static final String SERIALIZED_NAME_LNBITS_SERVICE_FEE = "lnbits_service_fee";
  @SerializedName(SERIALIZED_NAME_LNBITS_SERVICE_FEE)
  private BigDecimal lnbitsServiceFee = new BigDecimal("0");

  public static final String SERIALIZED_NAME_LNBITS_HIDE_API = "lnbits_hide_api";
  @SerializedName(SERIALIZED_NAME_LNBITS_HIDE_API)
  private Boolean lnbitsHideApi = false;

  public static final String SERIALIZED_NAME_LNBITS_DENOMINATION = "lnbits_denomination";
  @SerializedName(SERIALIZED_NAME_LNBITS_DENOMINATION)
  private String lnbitsDenomination = "sats";

  public static final String SERIALIZED_NAME_LNBITS_SITE_TITLE = "lnbits_site_title";
  @SerializedName(SERIALIZED_NAME_LNBITS_SITE_TITLE)
  private String lnbitsSiteTitle = "LNbits";

  public static final String SERIALIZED_NAME_LNBITS_SITE_TAGLINE = "lnbits_site_tagline";
  @SerializedName(SERIALIZED_NAME_LNBITS_SITE_TAGLINE)
  private String lnbitsSiteTagline = "free and open-source lightning wallet";

  public static final String SERIALIZED_NAME_LNBITS_SITE_DESCRIPTION = "lnbits_site_description";
  @SerializedName(SERIALIZED_NAME_LNBITS_SITE_DESCRIPTION)
  private String lnbitsSiteDescription;

  public static final String SERIALIZED_NAME_LNBITS_DEFAULT_WALLET_NAME = "lnbits_default_wallet_name";
  @SerializedName(SERIALIZED_NAME_LNBITS_DEFAULT_WALLET_NAME)
  private String lnbitsDefaultWalletName = "LNbits wallet";

  public static final String SERIALIZED_NAME_LNBITS_THEME_OPTIONS = "lnbits_theme_options";
  @SerializedName(SERIALIZED_NAME_LNBITS_THEME_OPTIONS)
  private List<String> lnbitsThemeOptions = new ArrayList<>(Arrays.asList("classic", "freedom", "mint", "salvador", "monochrome", "autumn", "cyber"));

  public static final String SERIALIZED_NAME_LNBITS_CUSTOM_LOGO = "lnbits_custom_logo";
  @SerializedName(SERIALIZED_NAME_LNBITS_CUSTOM_LOGO)
  private String lnbitsCustomLogo;

  public static final String SERIALIZED_NAME_LNBITS_AD_SPACE_TITLE = "lnbits_ad_space_title";
  @SerializedName(SERIALIZED_NAME_LNBITS_AD_SPACE_TITLE)
  private String lnbitsAdSpaceTitle = "Supported by";

  public static final String SERIALIZED_NAME_LNBITS_AD_SPACE = "lnbits_ad_space";
  @SerializedName(SERIALIZED_NAME_LNBITS_AD_SPACE)
  private String lnbitsAdSpace = "https://shop.lnbits.com/;/static/images/lnbits-shop-light.png;/static/images/lnbits-shop-dark.png";

  public static final String SERIALIZED_NAME_LNBITS_AD_SPACE_ENABLED = "lnbits_ad_space_enabled";
  @SerializedName(SERIALIZED_NAME_LNBITS_AD_SPACE_ENABLED)
  private Boolean lnbitsAdSpaceEnabled = false;

  public static final String SERIALIZED_NAME_LNBITS_ALLOWED_CURRENCIES = "lnbits_allowed_currencies";
  @SerializedName(SERIALIZED_NAME_LNBITS_ALLOWED_CURRENCIES)
  private List<String> lnbitsAllowedCurrencies = null;

  public static final String SERIALIZED_NAME_LNBITS_ADMIN_EXTENSIONS = "lnbits_admin_extensions";
  @SerializedName(SERIALIZED_NAME_LNBITS_ADMIN_EXTENSIONS)
  private List<String> lnbitsAdminExtensions = null;

  public static final String SERIALIZED_NAME_LNBITS_EXTENSIONS_MANIFESTS = "lnbits_extensions_manifests";
  @SerializedName(SERIALIZED_NAME_LNBITS_EXTENSIONS_MANIFESTS)
  private List<String> lnbitsExtensionsManifests = new ArrayList<>(Arrays.asList("https://raw.githubusercontent.com/lnbits/lnbits-extensions/main/extensions.json"));

  public static final String SERIALIZED_NAME_LNBITS_ADMIN_USERS = "lnbits_admin_users";
  @SerializedName(SERIALIZED_NAME_LNBITS_ADMIN_USERS)
  private List<String> lnbitsAdminUsers = null;

  public static final String SERIALIZED_NAME_LNBITS_ALLOWED_USERS = "lnbits_allowed_users";
  @SerializedName(SERIALIZED_NAME_LNBITS_ALLOWED_USERS)
  private List<String> lnbitsAllowedUsers = null;

  public EditableSettings() {
  }

  public EditableSettings lightningInvoiceExpiry(Integer lightningInvoiceExpiry) {
    
    this.lightningInvoiceExpiry = lightningInvoiceExpiry;
    return this;
  }

   /**
   * Get lightningInvoiceExpiry
   * @return lightningInvoiceExpiry
  **/
  @javax.annotation.Nullable
  public Integer getLightningInvoiceExpiry() {
    return lightningInvoiceExpiry;
  }


  public void setLightningInvoiceExpiry(Integer lightningInvoiceExpiry) {
    this.lightningInvoiceExpiry = lightningInvoiceExpiry;
  }


  public EditableSettings boltzNetwork(String boltzNetwork) {
    
    this.boltzNetwork = boltzNetwork;
    return this;
  }

   /**
   * Get boltzNetwork
   * @return boltzNetwork
  **/
  @javax.annotation.Nullable
  public String getBoltzNetwork() {
    return boltzNetwork;
  }


  public void setBoltzNetwork(String boltzNetwork) {
    this.boltzNetwork = boltzNetwork;
  }


  public EditableSettings boltzUrl(String boltzUrl) {
    
    this.boltzUrl = boltzUrl;
    return this;
  }

   /**
   * Get boltzUrl
   * @return boltzUrl
  **/
  @javax.annotation.Nullable
  public String getBoltzUrl() {
    return boltzUrl;
  }


  public void setBoltzUrl(String boltzUrl) {
    this.boltzUrl = boltzUrl;
  }


  public EditableSettings boltzMempoolSpaceUrl(String boltzMempoolSpaceUrl) {
    
    this.boltzMempoolSpaceUrl = boltzMempoolSpaceUrl;
    return this;
  }

   /**
   * Get boltzMempoolSpaceUrl
   * @return boltzMempoolSpaceUrl
  **/
  @javax.annotation.Nullable
  public String getBoltzMempoolSpaceUrl() {
    return boltzMempoolSpaceUrl;
  }


  public void setBoltzMempoolSpaceUrl(String boltzMempoolSpaceUrl) {
    this.boltzMempoolSpaceUrl = boltzMempoolSpaceUrl;
  }


  public EditableSettings boltzMempoolSpaceUrlWs(String boltzMempoolSpaceUrlWs) {
    
    this.boltzMempoolSpaceUrlWs = boltzMempoolSpaceUrlWs;
    return this;
  }

   /**
   * Get boltzMempoolSpaceUrlWs
   * @return boltzMempoolSpaceUrlWs
  **/
  @javax.annotation.Nullable
  public String getBoltzMempoolSpaceUrlWs() {
    return boltzMempoolSpaceUrlWs;
  }


  public void setBoltzMempoolSpaceUrlWs(String boltzMempoolSpaceUrlWs) {
    this.boltzMempoolSpaceUrlWs = boltzMempoolSpaceUrlWs;
  }


  public EditableSettings lntipsApiEndpoint(String lntipsApiEndpoint) {
    
    this.lntipsApiEndpoint = lntipsApiEndpoint;
    return this;
  }

   /**
   * Get lntipsApiEndpoint
   * @return lntipsApiEndpoint
  **/
  @javax.annotation.Nullable
  public String getLntipsApiEndpoint() {
    return lntipsApiEndpoint;
  }


  public void setLntipsApiEndpoint(String lntipsApiEndpoint) {
    this.lntipsApiEndpoint = lntipsApiEndpoint;
  }


  public EditableSettings lntipsApiKey(String lntipsApiKey) {
    
    this.lntipsApiKey = lntipsApiKey;
    return this;
  }

   /**
   * Get lntipsApiKey
   * @return lntipsApiKey
  **/
  @javax.annotation.Nullable
  public String getLntipsApiKey() {
    return lntipsApiKey;
  }


  public void setLntipsApiKey(String lntipsApiKey) {
    this.lntipsApiKey = lntipsApiKey;
  }


  public EditableSettings lntipsAdminKey(String lntipsAdminKey) {
    
    this.lntipsAdminKey = lntipsAdminKey;
    return this;
  }

   /**
   * Get lntipsAdminKey
   * @return lntipsAdminKey
  **/
  @javax.annotation.Nullable
  public String getLntipsAdminKey() {
    return lntipsAdminKey;
  }


  public void setLntipsAdminKey(String lntipsAdminKey) {
    this.lntipsAdminKey = lntipsAdminKey;
  }


  public EditableSettings lntipsInvoiceKey(String lntipsInvoiceKey) {
    
    this.lntipsInvoiceKey = lntipsInvoiceKey;
    return this;
  }

   /**
   * Get lntipsInvoiceKey
   * @return lntipsInvoiceKey
  **/
  @javax.annotation.Nullable
  public String getLntipsInvoiceKey() {
    return lntipsInvoiceKey;
  }


  public void setLntipsInvoiceKey(String lntipsInvoiceKey) {
    this.lntipsInvoiceKey = lntipsInvoiceKey;
  }


  public EditableSettings sparkUrl(String sparkUrl) {
    
    this.sparkUrl = sparkUrl;
    return this;
  }

   /**
   * Get sparkUrl
   * @return sparkUrl
  **/
  @javax.annotation.Nullable
  public String getSparkUrl() {
    return sparkUrl;
  }


  public void setSparkUrl(String sparkUrl) {
    this.sparkUrl = sparkUrl;
  }


  public EditableSettings sparkToken(String sparkToken) {
    
    this.sparkToken = sparkToken;
    return this;
  }

   /**
   * Get sparkToken
   * @return sparkToken
  **/
  @javax.annotation.Nullable
  public String getSparkToken() {
    return sparkToken;
  }


  public void setSparkToken(String sparkToken) {
    this.sparkToken = sparkToken;
  }


  public EditableSettings opennodeApiEndpoint(String opennodeApiEndpoint) {
    
    this.opennodeApiEndpoint = opennodeApiEndpoint;
    return this;
  }

   /**
   * Get opennodeApiEndpoint
   * @return opennodeApiEndpoint
  **/
  @javax.annotation.Nullable
  public String getOpennodeApiEndpoint() {
    return opennodeApiEndpoint;
  }


  public void setOpennodeApiEndpoint(String opennodeApiEndpoint) {
    this.opennodeApiEndpoint = opennodeApiEndpoint;
  }


  public EditableSettings opennodeKey(String opennodeKey) {
    
    this.opennodeKey = opennodeKey;
    return this;
  }

   /**
   * Get opennodeKey
   * @return opennodeKey
  **/
  @javax.annotation.Nullable
  public String getOpennodeKey() {
    return opennodeKey;
  }


  public void setOpennodeKey(String opennodeKey) {
    this.opennodeKey = opennodeKey;
  }


  public EditableSettings opennodeAdminKey(String opennodeAdminKey) {
    
    this.opennodeAdminKey = opennodeAdminKey;
    return this;
  }

   /**
   * Get opennodeAdminKey
   * @return opennodeAdminKey
  **/
  @javax.annotation.Nullable
  public String getOpennodeAdminKey() {
    return opennodeAdminKey;
  }


  public void setOpennodeAdminKey(String opennodeAdminKey) {
    this.opennodeAdminKey = opennodeAdminKey;
  }


  public EditableSettings opennodeInvoiceKey(String opennodeInvoiceKey) {
    
    this.opennodeInvoiceKey = opennodeInvoiceKey;
    return this;
  }

   /**
   * Get opennodeInvoiceKey
   * @return opennodeInvoiceKey
  **/
  @javax.annotation.Nullable
  public String getOpennodeInvoiceKey() {
    return opennodeInvoiceKey;
  }


  public void setOpennodeInvoiceKey(String opennodeInvoiceKey) {
    this.opennodeInvoiceKey = opennodeInvoiceKey;
  }


  public EditableSettings lnpayApiEndpoint(String lnpayApiEndpoint) {
    
    this.lnpayApiEndpoint = lnpayApiEndpoint;
    return this;
  }

   /**
   * Get lnpayApiEndpoint
   * @return lnpayApiEndpoint
  **/
  @javax.annotation.Nullable
  public String getLnpayApiEndpoint() {
    return lnpayApiEndpoint;
  }


  public void setLnpayApiEndpoint(String lnpayApiEndpoint) {
    this.lnpayApiEndpoint = lnpayApiEndpoint;
  }


  public EditableSettings lnpayApiKey(String lnpayApiKey) {
    
    this.lnpayApiKey = lnpayApiKey;
    return this;
  }

   /**
   * Get lnpayApiKey
   * @return lnpayApiKey
  **/
  @javax.annotation.Nullable
  public String getLnpayApiKey() {
    return lnpayApiKey;
  }


  public void setLnpayApiKey(String lnpayApiKey) {
    this.lnpayApiKey = lnpayApiKey;
  }


  public EditableSettings lnpayWalletKey(String lnpayWalletKey) {
    
    this.lnpayWalletKey = lnpayWalletKey;
    return this;
  }

   /**
   * Get lnpayWalletKey
   * @return lnpayWalletKey
  **/
  @javax.annotation.Nullable
  public String getLnpayWalletKey() {
    return lnpayWalletKey;
  }


  public void setLnpayWalletKey(String lnpayWalletKey) {
    this.lnpayWalletKey = lnpayWalletKey;
  }


  public EditableSettings lnpayAdminKey(String lnpayAdminKey) {
    
    this.lnpayAdminKey = lnpayAdminKey;
    return this;
  }

   /**
   * Get lnpayAdminKey
   * @return lnpayAdminKey
  **/
  @javax.annotation.Nullable
  public String getLnpayAdminKey() {
    return lnpayAdminKey;
  }


  public void setLnpayAdminKey(String lnpayAdminKey) {
    this.lnpayAdminKey = lnpayAdminKey;
  }


  public EditableSettings lndGrpcEndpoint(String lndGrpcEndpoint) {
    
    this.lndGrpcEndpoint = lndGrpcEndpoint;
    return this;
  }

   /**
   * Get lndGrpcEndpoint
   * @return lndGrpcEndpoint
  **/
  @javax.annotation.Nullable
  public String getLndGrpcEndpoint() {
    return lndGrpcEndpoint;
  }


  public void setLndGrpcEndpoint(String lndGrpcEndpoint) {
    this.lndGrpcEndpoint = lndGrpcEndpoint;
  }


  public EditableSettings lndGrpcCert(String lndGrpcCert) {
    
    this.lndGrpcCert = lndGrpcCert;
    return this;
  }

   /**
   * Get lndGrpcCert
   * @return lndGrpcCert
  **/
  @javax.annotation.Nullable
  public String getLndGrpcCert() {
    return lndGrpcCert;
  }


  public void setLndGrpcCert(String lndGrpcCert) {
    this.lndGrpcCert = lndGrpcCert;
  }


  public EditableSettings lndGrpcPort(Integer lndGrpcPort) {
    
    this.lndGrpcPort = lndGrpcPort;
    return this;
  }

   /**
   * Get lndGrpcPort
   * @return lndGrpcPort
  **/
  @javax.annotation.Nullable
  public Integer getLndGrpcPort() {
    return lndGrpcPort;
  }


  public void setLndGrpcPort(Integer lndGrpcPort) {
    this.lndGrpcPort = lndGrpcPort;
  }


  public EditableSettings lndGrpcAdminMacaroon(String lndGrpcAdminMacaroon) {
    
    this.lndGrpcAdminMacaroon = lndGrpcAdminMacaroon;
    return this;
  }

   /**
   * Get lndGrpcAdminMacaroon
   * @return lndGrpcAdminMacaroon
  **/
  @javax.annotation.Nullable
  public String getLndGrpcAdminMacaroon() {
    return lndGrpcAdminMacaroon;
  }


  public void setLndGrpcAdminMacaroon(String lndGrpcAdminMacaroon) {
    this.lndGrpcAdminMacaroon = lndGrpcAdminMacaroon;
  }


  public EditableSettings lndGrpcInvoiceMacaroon(String lndGrpcInvoiceMacaroon) {
    
    this.lndGrpcInvoiceMacaroon = lndGrpcInvoiceMacaroon;
    return this;
  }

   /**
   * Get lndGrpcInvoiceMacaroon
   * @return lndGrpcInvoiceMacaroon
  **/
  @javax.annotation.Nullable
  public String getLndGrpcInvoiceMacaroon() {
    return lndGrpcInvoiceMacaroon;
  }


  public void setLndGrpcInvoiceMacaroon(String lndGrpcInvoiceMacaroon) {
    this.lndGrpcInvoiceMacaroon = lndGrpcInvoiceMacaroon;
  }


  public EditableSettings lndGrpcMacaroon(String lndGrpcMacaroon) {
    
    this.lndGrpcMacaroon = lndGrpcMacaroon;
    return this;
  }

   /**
   * Get lndGrpcMacaroon
   * @return lndGrpcMacaroon
  **/
  @javax.annotation.Nullable
  public String getLndGrpcMacaroon() {
    return lndGrpcMacaroon;
  }


  public void setLndGrpcMacaroon(String lndGrpcMacaroon) {
    this.lndGrpcMacaroon = lndGrpcMacaroon;
  }


  public EditableSettings lndGrpcMacaroonEncrypted(String lndGrpcMacaroonEncrypted) {
    
    this.lndGrpcMacaroonEncrypted = lndGrpcMacaroonEncrypted;
    return this;
  }

   /**
   * Get lndGrpcMacaroonEncrypted
   * @return lndGrpcMacaroonEncrypted
  **/
  @javax.annotation.Nullable
  public String getLndGrpcMacaroonEncrypted() {
    return lndGrpcMacaroonEncrypted;
  }


  public void setLndGrpcMacaroonEncrypted(String lndGrpcMacaroonEncrypted) {
    this.lndGrpcMacaroonEncrypted = lndGrpcMacaroonEncrypted;
  }


  public EditableSettings lndRestEndpoint(String lndRestEndpoint) {
    
    this.lndRestEndpoint = lndRestEndpoint;
    return this;
  }

   /**
   * Get lndRestEndpoint
   * @return lndRestEndpoint
  **/
  @javax.annotation.Nullable
  public String getLndRestEndpoint() {
    return lndRestEndpoint;
  }


  public void setLndRestEndpoint(String lndRestEndpoint) {
    this.lndRestEndpoint = lndRestEndpoint;
  }


  public EditableSettings lndRestCert(String lndRestCert) {
    
    this.lndRestCert = lndRestCert;
    return this;
  }

   /**
   * Get lndRestCert
   * @return lndRestCert
  **/
  @javax.annotation.Nullable
  public String getLndRestCert() {
    return lndRestCert;
  }


  public void setLndRestCert(String lndRestCert) {
    this.lndRestCert = lndRestCert;
  }


  public EditableSettings lndRestMacaroon(String lndRestMacaroon) {
    
    this.lndRestMacaroon = lndRestMacaroon;
    return this;
  }

   /**
   * Get lndRestMacaroon
   * @return lndRestMacaroon
  **/
  @javax.annotation.Nullable
  public String getLndRestMacaroon() {
    return lndRestMacaroon;
  }


  public void setLndRestMacaroon(String lndRestMacaroon) {
    this.lndRestMacaroon = lndRestMacaroon;
  }


  public EditableSettings lndRestMacaroonEncrypted(String lndRestMacaroonEncrypted) {
    
    this.lndRestMacaroonEncrypted = lndRestMacaroonEncrypted;
    return this;
  }

   /**
   * Get lndRestMacaroonEncrypted
   * @return lndRestMacaroonEncrypted
  **/
  @javax.annotation.Nullable
  public String getLndRestMacaroonEncrypted() {
    return lndRestMacaroonEncrypted;
  }


  public void setLndRestMacaroonEncrypted(String lndRestMacaroonEncrypted) {
    this.lndRestMacaroonEncrypted = lndRestMacaroonEncrypted;
  }


  public EditableSettings lndCert(String lndCert) {
    
    this.lndCert = lndCert;
    return this;
  }

   /**
   * Get lndCert
   * @return lndCert
  **/
  @javax.annotation.Nullable
  public String getLndCert() {
    return lndCert;
  }


  public void setLndCert(String lndCert) {
    this.lndCert = lndCert;
  }


  public EditableSettings lndAdminMacaroon(String lndAdminMacaroon) {
    
    this.lndAdminMacaroon = lndAdminMacaroon;
    return this;
  }

   /**
   * Get lndAdminMacaroon
   * @return lndAdminMacaroon
  **/
  @javax.annotation.Nullable
  public String getLndAdminMacaroon() {
    return lndAdminMacaroon;
  }


  public void setLndAdminMacaroon(String lndAdminMacaroon) {
    this.lndAdminMacaroon = lndAdminMacaroon;
  }


  public EditableSettings lndInvoiceMacaroon(String lndInvoiceMacaroon) {
    
    this.lndInvoiceMacaroon = lndInvoiceMacaroon;
    return this;
  }

   /**
   * Get lndInvoiceMacaroon
   * @return lndInvoiceMacaroon
  **/
  @javax.annotation.Nullable
  public String getLndInvoiceMacaroon() {
    return lndInvoiceMacaroon;
  }


  public void setLndInvoiceMacaroon(String lndInvoiceMacaroon) {
    this.lndInvoiceMacaroon = lndInvoiceMacaroon;
  }


  public EditableSettings lndRestAdminMacaroon(String lndRestAdminMacaroon) {
    
    this.lndRestAdminMacaroon = lndRestAdminMacaroon;
    return this;
  }

   /**
   * Get lndRestAdminMacaroon
   * @return lndRestAdminMacaroon
  **/
  @javax.annotation.Nullable
  public String getLndRestAdminMacaroon() {
    return lndRestAdminMacaroon;
  }


  public void setLndRestAdminMacaroon(String lndRestAdminMacaroon) {
    this.lndRestAdminMacaroon = lndRestAdminMacaroon;
  }


  public EditableSettings lndRestInvoiceMacaroon(String lndRestInvoiceMacaroon) {
    
    this.lndRestInvoiceMacaroon = lndRestInvoiceMacaroon;
    return this;
  }

   /**
   * Get lndRestInvoiceMacaroon
   * @return lndRestInvoiceMacaroon
  **/
  @javax.annotation.Nullable
  public String getLndRestInvoiceMacaroon() {
    return lndRestInvoiceMacaroon;
  }


  public void setLndRestInvoiceMacaroon(String lndRestInvoiceMacaroon) {
    this.lndRestInvoiceMacaroon = lndRestInvoiceMacaroon;
  }


  public EditableSettings eclairUrl(String eclairUrl) {
    
    this.eclairUrl = eclairUrl;
    return this;
  }

   /**
   * Get eclairUrl
   * @return eclairUrl
  **/
  @javax.annotation.Nullable
  public String getEclairUrl() {
    return eclairUrl;
  }


  public void setEclairUrl(String eclairUrl) {
    this.eclairUrl = eclairUrl;
  }


  public EditableSettings eclairPass(String eclairPass) {
    
    this.eclairPass = eclairPass;
    return this;
  }

   /**
   * Get eclairPass
   * @return eclairPass
  **/
  @javax.annotation.Nullable
  public String getEclairPass() {
    return eclairPass;
  }


  public void setEclairPass(String eclairPass) {
    this.eclairPass = eclairPass;
  }


  public EditableSettings corelightningRpc(String corelightningRpc) {
    
    this.corelightningRpc = corelightningRpc;
    return this;
  }

   /**
   * Get corelightningRpc
   * @return corelightningRpc
  **/
  @javax.annotation.Nullable
  public String getCorelightningRpc() {
    return corelightningRpc;
  }


  public void setCorelightningRpc(String corelightningRpc) {
    this.corelightningRpc = corelightningRpc;
  }


  public EditableSettings clightningRpc(String clightningRpc) {
    
    this.clightningRpc = clightningRpc;
    return this;
  }

   /**
   * Get clightningRpc
   * @return clightningRpc
  **/
  @javax.annotation.Nullable
  public String getClightningRpc() {
    return clightningRpc;
  }


  public void setClightningRpc(String clightningRpc) {
    this.clightningRpc = clightningRpc;
  }


  public EditableSettings clicheEndpoint(String clicheEndpoint) {
    
    this.clicheEndpoint = clicheEndpoint;
    return this;
  }

   /**
   * Get clicheEndpoint
   * @return clicheEndpoint
  **/
  @javax.annotation.Nullable
  public String getClicheEndpoint() {
    return clicheEndpoint;
  }


  public void setClicheEndpoint(String clicheEndpoint) {
    this.clicheEndpoint = clicheEndpoint;
  }


  public EditableSettings lnbitsEndpoint(String lnbitsEndpoint) {
    
    this.lnbitsEndpoint = lnbitsEndpoint;
    return this;
  }

   /**
   * Get lnbitsEndpoint
   * @return lnbitsEndpoint
  **/
  @javax.annotation.Nullable
  public String getLnbitsEndpoint() {
    return lnbitsEndpoint;
  }


  public void setLnbitsEndpoint(String lnbitsEndpoint) {
    this.lnbitsEndpoint = lnbitsEndpoint;
  }


  public EditableSettings lnbitsKey(String lnbitsKey) {
    
    this.lnbitsKey = lnbitsKey;
    return this;
  }

   /**
   * Get lnbitsKey
   * @return lnbitsKey
  **/
  @javax.annotation.Nullable
  public String getLnbitsKey() {
    return lnbitsKey;
  }


  public void setLnbitsKey(String lnbitsKey) {
    this.lnbitsKey = lnbitsKey;
  }


  public EditableSettings lnbitsAdminKey(String lnbitsAdminKey) {
    
    this.lnbitsAdminKey = lnbitsAdminKey;
    return this;
  }

   /**
   * Get lnbitsAdminKey
   * @return lnbitsAdminKey
  **/
  @javax.annotation.Nullable
  public String getLnbitsAdminKey() {
    return lnbitsAdminKey;
  }


  public void setLnbitsAdminKey(String lnbitsAdminKey) {
    this.lnbitsAdminKey = lnbitsAdminKey;
  }


  public EditableSettings lnbitsInvoiceKey(String lnbitsInvoiceKey) {
    
    this.lnbitsInvoiceKey = lnbitsInvoiceKey;
    return this;
  }

   /**
   * Get lnbitsInvoiceKey
   * @return lnbitsInvoiceKey
  **/
  @javax.annotation.Nullable
  public String getLnbitsInvoiceKey() {
    return lnbitsInvoiceKey;
  }


  public void setLnbitsInvoiceKey(String lnbitsInvoiceKey) {
    this.lnbitsInvoiceKey = lnbitsInvoiceKey;
  }


  public EditableSettings fakeWalletSecret(String fakeWalletSecret) {
    
    this.fakeWalletSecret = fakeWalletSecret;
    return this;
  }

   /**
   * Get fakeWalletSecret
   * @return fakeWalletSecret
  **/
  @javax.annotation.Nullable
  public String getFakeWalletSecret() {
    return fakeWalletSecret;
  }


  public void setFakeWalletSecret(String fakeWalletSecret) {
    this.fakeWalletSecret = fakeWalletSecret;
  }


  public EditableSettings lnbitsBackendWalletClass(String lnbitsBackendWalletClass) {
    
    this.lnbitsBackendWalletClass = lnbitsBackendWalletClass;
    return this;
  }

   /**
   * Get lnbitsBackendWalletClass
   * @return lnbitsBackendWalletClass
  **/
  @javax.annotation.Nullable
  public String getLnbitsBackendWalletClass() {
    return lnbitsBackendWalletClass;
  }


  public void setLnbitsBackendWalletClass(String lnbitsBackendWalletClass) {
    this.lnbitsBackendWalletClass = lnbitsBackendWalletClass;
  }


  public EditableSettings lnbitsRateLimitNo(String lnbitsRateLimitNo) {
    
    this.lnbitsRateLimitNo = lnbitsRateLimitNo;
    return this;
  }

   /**
   * Get lnbitsRateLimitNo
   * @return lnbitsRateLimitNo
  **/
  @javax.annotation.Nullable
  public String getLnbitsRateLimitNo() {
    return lnbitsRateLimitNo;
  }


  public void setLnbitsRateLimitNo(String lnbitsRateLimitNo) {
    this.lnbitsRateLimitNo = lnbitsRateLimitNo;
  }


  public EditableSettings lnbitsRateLimitUnit(String lnbitsRateLimitUnit) {
    
    this.lnbitsRateLimitUnit = lnbitsRateLimitUnit;
    return this;
  }

   /**
   * Get lnbitsRateLimitUnit
   * @return lnbitsRateLimitUnit
  **/
  @javax.annotation.Nullable
  public String getLnbitsRateLimitUnit() {
    return lnbitsRateLimitUnit;
  }


  public void setLnbitsRateLimitUnit(String lnbitsRateLimitUnit) {
    this.lnbitsRateLimitUnit = lnbitsRateLimitUnit;
  }


  public EditableSettings lnbitsAllowedIps(List<String> lnbitsAllowedIps) {
    
    this.lnbitsAllowedIps = lnbitsAllowedIps;
    return this;
  }

  public EditableSettings addLnbitsAllowedIpsItem(String lnbitsAllowedIpsItem) {
    if (this.lnbitsAllowedIps == null) {
      this.lnbitsAllowedIps = null;
    }
    this.lnbitsAllowedIps.add(lnbitsAllowedIpsItem);
    return this;
  }

   /**
   * Get lnbitsAllowedIps
   * @return lnbitsAllowedIps
  **/
  @javax.annotation.Nullable
  public List<String> getLnbitsAllowedIps() {
    return lnbitsAllowedIps;
  }


  public void setLnbitsAllowedIps(List<String> lnbitsAllowedIps) {
    this.lnbitsAllowedIps = lnbitsAllowedIps;
  }


  public EditableSettings lnbitsBlockedIps(List<String> lnbitsBlockedIps) {
    
    this.lnbitsBlockedIps = lnbitsBlockedIps;
    return this;
  }

  public EditableSettings addLnbitsBlockedIpsItem(String lnbitsBlockedIpsItem) {
    if (this.lnbitsBlockedIps == null) {
      this.lnbitsBlockedIps = null;
    }
    this.lnbitsBlockedIps.add(lnbitsBlockedIpsItem);
    return this;
  }

   /**
   * Get lnbitsBlockedIps
   * @return lnbitsBlockedIps
  **/
  @javax.annotation.Nullable
  public List<String> getLnbitsBlockedIps() {
    return lnbitsBlockedIps;
  }


  public void setLnbitsBlockedIps(List<String> lnbitsBlockedIps) {
    this.lnbitsBlockedIps = lnbitsBlockedIps;
  }


  public EditableSettings lnbitsNotifications(Boolean lnbitsNotifications) {
    
    this.lnbitsNotifications = lnbitsNotifications;
    return this;
  }

   /**
   * Get lnbitsNotifications
   * @return lnbitsNotifications
  **/
  @javax.annotation.Nullable
  public Boolean getLnbitsNotifications() {
    return lnbitsNotifications;
  }


  public void setLnbitsNotifications(Boolean lnbitsNotifications) {
    this.lnbitsNotifications = lnbitsNotifications;
  }


  public EditableSettings lnbitsKillswitch(Boolean lnbitsKillswitch) {
    
    this.lnbitsKillswitch = lnbitsKillswitch;
    return this;
  }

   /**
   * Get lnbitsKillswitch
   * @return lnbitsKillswitch
  **/
  @javax.annotation.Nullable
  public Boolean getLnbitsKillswitch() {
    return lnbitsKillswitch;
  }


  public void setLnbitsKillswitch(Boolean lnbitsKillswitch) {
    this.lnbitsKillswitch = lnbitsKillswitch;
  }


  public EditableSettings lnbitsKillswitchInterval(Integer lnbitsKillswitchInterval) {
    
    this.lnbitsKillswitchInterval = lnbitsKillswitchInterval;
    return this;
  }

   /**
   * Get lnbitsKillswitchInterval
   * @return lnbitsKillswitchInterval
  **/
  @javax.annotation.Nullable
  public Integer getLnbitsKillswitchInterval() {
    return lnbitsKillswitchInterval;
  }


  public void setLnbitsKillswitchInterval(Integer lnbitsKillswitchInterval) {
    this.lnbitsKillswitchInterval = lnbitsKillswitchInterval;
  }


  public EditableSettings lnbitsWatchdog(Boolean lnbitsWatchdog) {
    
    this.lnbitsWatchdog = lnbitsWatchdog;
    return this;
  }

   /**
   * Get lnbitsWatchdog
   * @return lnbitsWatchdog
  **/
  @javax.annotation.Nullable
  public Boolean getLnbitsWatchdog() {
    return lnbitsWatchdog;
  }


  public void setLnbitsWatchdog(Boolean lnbitsWatchdog) {
    this.lnbitsWatchdog = lnbitsWatchdog;
  }


  public EditableSettings lnbitsWatchdogInterval(Integer lnbitsWatchdogInterval) {
    
    this.lnbitsWatchdogInterval = lnbitsWatchdogInterval;
    return this;
  }

   /**
   * Get lnbitsWatchdogInterval
   * @return lnbitsWatchdogInterval
  **/
  @javax.annotation.Nullable
  public Integer getLnbitsWatchdogInterval() {
    return lnbitsWatchdogInterval;
  }


  public void setLnbitsWatchdogInterval(Integer lnbitsWatchdogInterval) {
    this.lnbitsWatchdogInterval = lnbitsWatchdogInterval;
  }


  public EditableSettings lnbitsWatchdogDelta(Integer lnbitsWatchdogDelta) {
    
    this.lnbitsWatchdogDelta = lnbitsWatchdogDelta;
    return this;
  }

   /**
   * Get lnbitsWatchdogDelta
   * @return lnbitsWatchdogDelta
  **/
  @javax.annotation.Nullable
  public Integer getLnbitsWatchdogDelta() {
    return lnbitsWatchdogDelta;
  }


  public void setLnbitsWatchdogDelta(Integer lnbitsWatchdogDelta) {
    this.lnbitsWatchdogDelta = lnbitsWatchdogDelta;
  }


  public EditableSettings lnbitsStatusManifest(String lnbitsStatusManifest) {
    
    this.lnbitsStatusManifest = lnbitsStatusManifest;
    return this;
  }

   /**
   * Get lnbitsStatusManifest
   * @return lnbitsStatusManifest
  **/
  @javax.annotation.Nullable
  public String getLnbitsStatusManifest() {
    return lnbitsStatusManifest;
  }


  public void setLnbitsStatusManifest(String lnbitsStatusManifest) {
    this.lnbitsStatusManifest = lnbitsStatusManifest;
  }


  public EditableSettings lnbitsBaseurl(String lnbitsBaseurl) {
    
    this.lnbitsBaseurl = lnbitsBaseurl;
    return this;
  }

   /**
   * Get lnbitsBaseurl
   * @return lnbitsBaseurl
  **/
  @javax.annotation.Nullable
  public String getLnbitsBaseurl() {
    return lnbitsBaseurl;
  }


  public void setLnbitsBaseurl(String lnbitsBaseurl) {
    this.lnbitsBaseurl = lnbitsBaseurl;
  }


  public EditableSettings lnbitsReserveFeeMin(Integer lnbitsReserveFeeMin) {
    
    this.lnbitsReserveFeeMin = lnbitsReserveFeeMin;
    return this;
  }

   /**
   * Get lnbitsReserveFeeMin
   * @return lnbitsReserveFeeMin
  **/
  @javax.annotation.Nullable
  public Integer getLnbitsReserveFeeMin() {
    return lnbitsReserveFeeMin;
  }


  public void setLnbitsReserveFeeMin(Integer lnbitsReserveFeeMin) {
    this.lnbitsReserveFeeMin = lnbitsReserveFeeMin;
  }


  public EditableSettings lnbitsReserveFeePercent(BigDecimal lnbitsReserveFeePercent) {
    
    this.lnbitsReserveFeePercent = lnbitsReserveFeePercent;
    return this;
  }

   /**
   * Get lnbitsReserveFeePercent
   * @return lnbitsReserveFeePercent
  **/
  @javax.annotation.Nullable
  public BigDecimal getLnbitsReserveFeePercent() {
    return lnbitsReserveFeePercent;
  }


  public void setLnbitsReserveFeePercent(BigDecimal lnbitsReserveFeePercent) {
    this.lnbitsReserveFeePercent = lnbitsReserveFeePercent;
  }


  public EditableSettings lnbitsServiceFee(BigDecimal lnbitsServiceFee) {
    
    this.lnbitsServiceFee = lnbitsServiceFee;
    return this;
  }

   /**
   * Get lnbitsServiceFee
   * @return lnbitsServiceFee
  **/
  @javax.annotation.Nullable
  public BigDecimal getLnbitsServiceFee() {
    return lnbitsServiceFee;
  }


  public void setLnbitsServiceFee(BigDecimal lnbitsServiceFee) {
    this.lnbitsServiceFee = lnbitsServiceFee;
  }


  public EditableSettings lnbitsHideApi(Boolean lnbitsHideApi) {
    
    this.lnbitsHideApi = lnbitsHideApi;
    return this;
  }

   /**
   * Get lnbitsHideApi
   * @return lnbitsHideApi
  **/
  @javax.annotation.Nullable
  public Boolean getLnbitsHideApi() {
    return lnbitsHideApi;
  }


  public void setLnbitsHideApi(Boolean lnbitsHideApi) {
    this.lnbitsHideApi = lnbitsHideApi;
  }


  public EditableSettings lnbitsDenomination(String lnbitsDenomination) {
    
    this.lnbitsDenomination = lnbitsDenomination;
    return this;
  }

   /**
   * Get lnbitsDenomination
   * @return lnbitsDenomination
  **/
  @javax.annotation.Nullable
  public String getLnbitsDenomination() {
    return lnbitsDenomination;
  }


  public void setLnbitsDenomination(String lnbitsDenomination) {
    this.lnbitsDenomination = lnbitsDenomination;
  }


  public EditableSettings lnbitsSiteTitle(String lnbitsSiteTitle) {
    
    this.lnbitsSiteTitle = lnbitsSiteTitle;
    return this;
  }

   /**
   * Get lnbitsSiteTitle
   * @return lnbitsSiteTitle
  **/
  @javax.annotation.Nullable
  public String getLnbitsSiteTitle() {
    return lnbitsSiteTitle;
  }


  public void setLnbitsSiteTitle(String lnbitsSiteTitle) {
    this.lnbitsSiteTitle = lnbitsSiteTitle;
  }


  public EditableSettings lnbitsSiteTagline(String lnbitsSiteTagline) {
    
    this.lnbitsSiteTagline = lnbitsSiteTagline;
    return this;
  }

   /**
   * Get lnbitsSiteTagline
   * @return lnbitsSiteTagline
  **/
  @javax.annotation.Nullable
  public String getLnbitsSiteTagline() {
    return lnbitsSiteTagline;
  }


  public void setLnbitsSiteTagline(String lnbitsSiteTagline) {
    this.lnbitsSiteTagline = lnbitsSiteTagline;
  }


  public EditableSettings lnbitsSiteDescription(String lnbitsSiteDescription) {
    
    this.lnbitsSiteDescription = lnbitsSiteDescription;
    return this;
  }

   /**
   * Get lnbitsSiteDescription
   * @return lnbitsSiteDescription
  **/
  @javax.annotation.Nullable
  public String getLnbitsSiteDescription() {
    return lnbitsSiteDescription;
  }


  public void setLnbitsSiteDescription(String lnbitsSiteDescription) {
    this.lnbitsSiteDescription = lnbitsSiteDescription;
  }


  public EditableSettings lnbitsDefaultWalletName(String lnbitsDefaultWalletName) {
    
    this.lnbitsDefaultWalletName = lnbitsDefaultWalletName;
    return this;
  }

   /**
   * Get lnbitsDefaultWalletName
   * @return lnbitsDefaultWalletName
  **/
  @javax.annotation.Nullable
  public String getLnbitsDefaultWalletName() {
    return lnbitsDefaultWalletName;
  }


  public void setLnbitsDefaultWalletName(String lnbitsDefaultWalletName) {
    this.lnbitsDefaultWalletName = lnbitsDefaultWalletName;
  }


  public EditableSettings lnbitsThemeOptions(List<String> lnbitsThemeOptions) {
    
    this.lnbitsThemeOptions = lnbitsThemeOptions;
    return this;
  }

  public EditableSettings addLnbitsThemeOptionsItem(String lnbitsThemeOptionsItem) {
    if (this.lnbitsThemeOptions == null) {
      this.lnbitsThemeOptions = new ArrayList<>(Arrays.asList("classic", "freedom", "mint", "salvador", "monochrome", "autumn", "cyber"));
    }
    this.lnbitsThemeOptions.add(lnbitsThemeOptionsItem);
    return this;
  }

   /**
   * Get lnbitsThemeOptions
   * @return lnbitsThemeOptions
  **/
  @javax.annotation.Nullable
  public List<String> getLnbitsThemeOptions() {
    return lnbitsThemeOptions;
  }


  public void setLnbitsThemeOptions(List<String> lnbitsThemeOptions) {
    this.lnbitsThemeOptions = lnbitsThemeOptions;
  }


  public EditableSettings lnbitsCustomLogo(String lnbitsCustomLogo) {
    
    this.lnbitsCustomLogo = lnbitsCustomLogo;
    return this;
  }

   /**
   * Get lnbitsCustomLogo
   * @return lnbitsCustomLogo
  **/
  @javax.annotation.Nullable
  public String getLnbitsCustomLogo() {
    return lnbitsCustomLogo;
  }


  public void setLnbitsCustomLogo(String lnbitsCustomLogo) {
    this.lnbitsCustomLogo = lnbitsCustomLogo;
  }


  public EditableSettings lnbitsAdSpaceTitle(String lnbitsAdSpaceTitle) {
    
    this.lnbitsAdSpaceTitle = lnbitsAdSpaceTitle;
    return this;
  }

   /**
   * Get lnbitsAdSpaceTitle
   * @return lnbitsAdSpaceTitle
  **/
  @javax.annotation.Nullable
  public String getLnbitsAdSpaceTitle() {
    return lnbitsAdSpaceTitle;
  }


  public void setLnbitsAdSpaceTitle(String lnbitsAdSpaceTitle) {
    this.lnbitsAdSpaceTitle = lnbitsAdSpaceTitle;
  }


  public EditableSettings lnbitsAdSpace(String lnbitsAdSpace) {
    
    this.lnbitsAdSpace = lnbitsAdSpace;
    return this;
  }

   /**
   * Get lnbitsAdSpace
   * @return lnbitsAdSpace
  **/
  @javax.annotation.Nullable
  public String getLnbitsAdSpace() {
    return lnbitsAdSpace;
  }


  public void setLnbitsAdSpace(String lnbitsAdSpace) {
    this.lnbitsAdSpace = lnbitsAdSpace;
  }


  public EditableSettings lnbitsAdSpaceEnabled(Boolean lnbitsAdSpaceEnabled) {
    
    this.lnbitsAdSpaceEnabled = lnbitsAdSpaceEnabled;
    return this;
  }

   /**
   * Get lnbitsAdSpaceEnabled
   * @return lnbitsAdSpaceEnabled
  **/
  @javax.annotation.Nullable
  public Boolean getLnbitsAdSpaceEnabled() {
    return lnbitsAdSpaceEnabled;
  }


  public void setLnbitsAdSpaceEnabled(Boolean lnbitsAdSpaceEnabled) {
    this.lnbitsAdSpaceEnabled = lnbitsAdSpaceEnabled;
  }


  public EditableSettings lnbitsAllowedCurrencies(List<String> lnbitsAllowedCurrencies) {
    
    this.lnbitsAllowedCurrencies = lnbitsAllowedCurrencies;
    return this;
  }

  public EditableSettings addLnbitsAllowedCurrenciesItem(String lnbitsAllowedCurrenciesItem) {
    if (this.lnbitsAllowedCurrencies == null) {
      this.lnbitsAllowedCurrencies = null;
    }
    this.lnbitsAllowedCurrencies.add(lnbitsAllowedCurrenciesItem);
    return this;
  }

   /**
   * Get lnbitsAllowedCurrencies
   * @return lnbitsAllowedCurrencies
  **/
  @javax.annotation.Nullable
  public List<String> getLnbitsAllowedCurrencies() {
    return lnbitsAllowedCurrencies;
  }


  public void setLnbitsAllowedCurrencies(List<String> lnbitsAllowedCurrencies) {
    this.lnbitsAllowedCurrencies = lnbitsAllowedCurrencies;
  }


  public EditableSettings lnbitsAdminExtensions(List<String> lnbitsAdminExtensions) {
    
    this.lnbitsAdminExtensions = lnbitsAdminExtensions;
    return this;
  }

  public EditableSettings addLnbitsAdminExtensionsItem(String lnbitsAdminExtensionsItem) {
    if (this.lnbitsAdminExtensions == null) {
      this.lnbitsAdminExtensions = null;
    }
    this.lnbitsAdminExtensions.add(lnbitsAdminExtensionsItem);
    return this;
  }

   /**
   * Get lnbitsAdminExtensions
   * @return lnbitsAdminExtensions
  **/
  @javax.annotation.Nullable
  public List<String> getLnbitsAdminExtensions() {
    return lnbitsAdminExtensions;
  }


  public void setLnbitsAdminExtensions(List<String> lnbitsAdminExtensions) {
    this.lnbitsAdminExtensions = lnbitsAdminExtensions;
  }


  public EditableSettings lnbitsExtensionsManifests(List<String> lnbitsExtensionsManifests) {
    
    this.lnbitsExtensionsManifests = lnbitsExtensionsManifests;
    return this;
  }

  public EditableSettings addLnbitsExtensionsManifestsItem(String lnbitsExtensionsManifestsItem) {
    if (this.lnbitsExtensionsManifests == null) {
      this.lnbitsExtensionsManifests = new ArrayList<>(Arrays.asList("https://raw.githubusercontent.com/lnbits/lnbits-extensions/main/extensions.json"));
    }
    this.lnbitsExtensionsManifests.add(lnbitsExtensionsManifestsItem);
    return this;
  }

   /**
   * Get lnbitsExtensionsManifests
   * @return lnbitsExtensionsManifests
  **/
  @javax.annotation.Nullable
  public List<String> getLnbitsExtensionsManifests() {
    return lnbitsExtensionsManifests;
  }


  public void setLnbitsExtensionsManifests(List<String> lnbitsExtensionsManifests) {
    this.lnbitsExtensionsManifests = lnbitsExtensionsManifests;
  }


  public EditableSettings lnbitsAdminUsers(List<String> lnbitsAdminUsers) {
    
    this.lnbitsAdminUsers = lnbitsAdminUsers;
    return this;
  }

  public EditableSettings addLnbitsAdminUsersItem(String lnbitsAdminUsersItem) {
    if (this.lnbitsAdminUsers == null) {
      this.lnbitsAdminUsers = null;
    }
    this.lnbitsAdminUsers.add(lnbitsAdminUsersItem);
    return this;
  }

   /**
   * Get lnbitsAdminUsers
   * @return lnbitsAdminUsers
  **/
  @javax.annotation.Nullable
  public List<String> getLnbitsAdminUsers() {
    return lnbitsAdminUsers;
  }


  public void setLnbitsAdminUsers(List<String> lnbitsAdminUsers) {
    this.lnbitsAdminUsers = lnbitsAdminUsers;
  }


  public EditableSettings lnbitsAllowedUsers(List<String> lnbitsAllowedUsers) {
    
    this.lnbitsAllowedUsers = lnbitsAllowedUsers;
    return this;
  }

  public EditableSettings addLnbitsAllowedUsersItem(String lnbitsAllowedUsersItem) {
    if (this.lnbitsAllowedUsers == null) {
      this.lnbitsAllowedUsers = null;
    }
    this.lnbitsAllowedUsers.add(lnbitsAllowedUsersItem);
    return this;
  }

   /**
   * Get lnbitsAllowedUsers
   * @return lnbitsAllowedUsers
  **/
  @javax.annotation.Nullable
  public List<String> getLnbitsAllowedUsers() {
    return lnbitsAllowedUsers;
  }


  public void setLnbitsAllowedUsers(List<String> lnbitsAllowedUsers) {
    this.lnbitsAllowedUsers = lnbitsAllowedUsers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditableSettings editableSettings = (EditableSettings) o;
    return Objects.equals(this.lightningInvoiceExpiry, editableSettings.lightningInvoiceExpiry) &&
        Objects.equals(this.boltzNetwork, editableSettings.boltzNetwork) &&
        Objects.equals(this.boltzUrl, editableSettings.boltzUrl) &&
        Objects.equals(this.boltzMempoolSpaceUrl, editableSettings.boltzMempoolSpaceUrl) &&
        Objects.equals(this.boltzMempoolSpaceUrlWs, editableSettings.boltzMempoolSpaceUrlWs) &&
        Objects.equals(this.lntipsApiEndpoint, editableSettings.lntipsApiEndpoint) &&
        Objects.equals(this.lntipsApiKey, editableSettings.lntipsApiKey) &&
        Objects.equals(this.lntipsAdminKey, editableSettings.lntipsAdminKey) &&
        Objects.equals(this.lntipsInvoiceKey, editableSettings.lntipsInvoiceKey) &&
        Objects.equals(this.sparkUrl, editableSettings.sparkUrl) &&
        Objects.equals(this.sparkToken, editableSettings.sparkToken) &&
        Objects.equals(this.opennodeApiEndpoint, editableSettings.opennodeApiEndpoint) &&
        Objects.equals(this.opennodeKey, editableSettings.opennodeKey) &&
        Objects.equals(this.opennodeAdminKey, editableSettings.opennodeAdminKey) &&
        Objects.equals(this.opennodeInvoiceKey, editableSettings.opennodeInvoiceKey) &&
        Objects.equals(this.lnpayApiEndpoint, editableSettings.lnpayApiEndpoint) &&
        Objects.equals(this.lnpayApiKey, editableSettings.lnpayApiKey) &&
        Objects.equals(this.lnpayWalletKey, editableSettings.lnpayWalletKey) &&
        Objects.equals(this.lnpayAdminKey, editableSettings.lnpayAdminKey) &&
        Objects.equals(this.lndGrpcEndpoint, editableSettings.lndGrpcEndpoint) &&
        Objects.equals(this.lndGrpcCert, editableSettings.lndGrpcCert) &&
        Objects.equals(this.lndGrpcPort, editableSettings.lndGrpcPort) &&
        Objects.equals(this.lndGrpcAdminMacaroon, editableSettings.lndGrpcAdminMacaroon) &&
        Objects.equals(this.lndGrpcInvoiceMacaroon, editableSettings.lndGrpcInvoiceMacaroon) &&
        Objects.equals(this.lndGrpcMacaroon, editableSettings.lndGrpcMacaroon) &&
        Objects.equals(this.lndGrpcMacaroonEncrypted, editableSettings.lndGrpcMacaroonEncrypted) &&
        Objects.equals(this.lndRestEndpoint, editableSettings.lndRestEndpoint) &&
        Objects.equals(this.lndRestCert, editableSettings.lndRestCert) &&
        Objects.equals(this.lndRestMacaroon, editableSettings.lndRestMacaroon) &&
        Objects.equals(this.lndRestMacaroonEncrypted, editableSettings.lndRestMacaroonEncrypted) &&
        Objects.equals(this.lndCert, editableSettings.lndCert) &&
        Objects.equals(this.lndAdminMacaroon, editableSettings.lndAdminMacaroon) &&
        Objects.equals(this.lndInvoiceMacaroon, editableSettings.lndInvoiceMacaroon) &&
        Objects.equals(this.lndRestAdminMacaroon, editableSettings.lndRestAdminMacaroon) &&
        Objects.equals(this.lndRestInvoiceMacaroon, editableSettings.lndRestInvoiceMacaroon) &&
        Objects.equals(this.eclairUrl, editableSettings.eclairUrl) &&
        Objects.equals(this.eclairPass, editableSettings.eclairPass) &&
        Objects.equals(this.corelightningRpc, editableSettings.corelightningRpc) &&
        Objects.equals(this.clightningRpc, editableSettings.clightningRpc) &&
        Objects.equals(this.clicheEndpoint, editableSettings.clicheEndpoint) &&
        Objects.equals(this.lnbitsEndpoint, editableSettings.lnbitsEndpoint) &&
        Objects.equals(this.lnbitsKey, editableSettings.lnbitsKey) &&
        Objects.equals(this.lnbitsAdminKey, editableSettings.lnbitsAdminKey) &&
        Objects.equals(this.lnbitsInvoiceKey, editableSettings.lnbitsInvoiceKey) &&
        Objects.equals(this.fakeWalletSecret, editableSettings.fakeWalletSecret) &&
        Objects.equals(this.lnbitsBackendWalletClass, editableSettings.lnbitsBackendWalletClass) &&
        Objects.equals(this.lnbitsRateLimitNo, editableSettings.lnbitsRateLimitNo) &&
        Objects.equals(this.lnbitsRateLimitUnit, editableSettings.lnbitsRateLimitUnit) &&
        Objects.equals(this.lnbitsAllowedIps, editableSettings.lnbitsAllowedIps) &&
        Objects.equals(this.lnbitsBlockedIps, editableSettings.lnbitsBlockedIps) &&
        Objects.equals(this.lnbitsNotifications, editableSettings.lnbitsNotifications) &&
        Objects.equals(this.lnbitsKillswitch, editableSettings.lnbitsKillswitch) &&
        Objects.equals(this.lnbitsKillswitchInterval, editableSettings.lnbitsKillswitchInterval) &&
        Objects.equals(this.lnbitsWatchdog, editableSettings.lnbitsWatchdog) &&
        Objects.equals(this.lnbitsWatchdogInterval, editableSettings.lnbitsWatchdogInterval) &&
        Objects.equals(this.lnbitsWatchdogDelta, editableSettings.lnbitsWatchdogDelta) &&
        Objects.equals(this.lnbitsStatusManifest, editableSettings.lnbitsStatusManifest) &&
        Objects.equals(this.lnbitsBaseurl, editableSettings.lnbitsBaseurl) &&
        Objects.equals(this.lnbitsReserveFeeMin, editableSettings.lnbitsReserveFeeMin) &&
        Objects.equals(this.lnbitsReserveFeePercent, editableSettings.lnbitsReserveFeePercent) &&
        Objects.equals(this.lnbitsServiceFee, editableSettings.lnbitsServiceFee) &&
        Objects.equals(this.lnbitsHideApi, editableSettings.lnbitsHideApi) &&
        Objects.equals(this.lnbitsDenomination, editableSettings.lnbitsDenomination) &&
        Objects.equals(this.lnbitsSiteTitle, editableSettings.lnbitsSiteTitle) &&
        Objects.equals(this.lnbitsSiteTagline, editableSettings.lnbitsSiteTagline) &&
        Objects.equals(this.lnbitsSiteDescription, editableSettings.lnbitsSiteDescription) &&
        Objects.equals(this.lnbitsDefaultWalletName, editableSettings.lnbitsDefaultWalletName) &&
        Objects.equals(this.lnbitsThemeOptions, editableSettings.lnbitsThemeOptions) &&
        Objects.equals(this.lnbitsCustomLogo, editableSettings.lnbitsCustomLogo) &&
        Objects.equals(this.lnbitsAdSpaceTitle, editableSettings.lnbitsAdSpaceTitle) &&
        Objects.equals(this.lnbitsAdSpace, editableSettings.lnbitsAdSpace) &&
        Objects.equals(this.lnbitsAdSpaceEnabled, editableSettings.lnbitsAdSpaceEnabled) &&
        Objects.equals(this.lnbitsAllowedCurrencies, editableSettings.lnbitsAllowedCurrencies) &&
        Objects.equals(this.lnbitsAdminExtensions, editableSettings.lnbitsAdminExtensions) &&
        Objects.equals(this.lnbitsExtensionsManifests, editableSettings.lnbitsExtensionsManifests) &&
        Objects.equals(this.lnbitsAdminUsers, editableSettings.lnbitsAdminUsers) &&
        Objects.equals(this.lnbitsAllowedUsers, editableSettings.lnbitsAllowedUsers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lightningInvoiceExpiry, boltzNetwork, boltzUrl, boltzMempoolSpaceUrl, boltzMempoolSpaceUrlWs, lntipsApiEndpoint, lntipsApiKey, lntipsAdminKey, lntipsInvoiceKey, sparkUrl, sparkToken, opennodeApiEndpoint, opennodeKey, opennodeAdminKey, opennodeInvoiceKey, lnpayApiEndpoint, lnpayApiKey, lnpayWalletKey, lnpayAdminKey, lndGrpcEndpoint, lndGrpcCert, lndGrpcPort, lndGrpcAdminMacaroon, lndGrpcInvoiceMacaroon, lndGrpcMacaroon, lndGrpcMacaroonEncrypted, lndRestEndpoint, lndRestCert, lndRestMacaroon, lndRestMacaroonEncrypted, lndCert, lndAdminMacaroon, lndInvoiceMacaroon, lndRestAdminMacaroon, lndRestInvoiceMacaroon, eclairUrl, eclairPass, corelightningRpc, clightningRpc, clicheEndpoint, lnbitsEndpoint, lnbitsKey, lnbitsAdminKey, lnbitsInvoiceKey, fakeWalletSecret, lnbitsBackendWalletClass, lnbitsRateLimitNo, lnbitsRateLimitUnit, lnbitsAllowedIps, lnbitsBlockedIps, lnbitsNotifications, lnbitsKillswitch, lnbitsKillswitchInterval, lnbitsWatchdog, lnbitsWatchdogInterval, lnbitsWatchdogDelta, lnbitsStatusManifest, lnbitsBaseurl, lnbitsReserveFeeMin, lnbitsReserveFeePercent, lnbitsServiceFee, lnbitsHideApi, lnbitsDenomination, lnbitsSiteTitle, lnbitsSiteTagline, lnbitsSiteDescription, lnbitsDefaultWalletName, lnbitsThemeOptions, lnbitsCustomLogo, lnbitsAdSpaceTitle, lnbitsAdSpace, lnbitsAdSpaceEnabled, lnbitsAllowedCurrencies, lnbitsAdminExtensions, lnbitsExtensionsManifests, lnbitsAdminUsers, lnbitsAllowedUsers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditableSettings {\n");
    sb.append("    lightningInvoiceExpiry: ").append(toIndentedString(lightningInvoiceExpiry)).append("\n");
    sb.append("    boltzNetwork: ").append(toIndentedString(boltzNetwork)).append("\n");
    sb.append("    boltzUrl: ").append(toIndentedString(boltzUrl)).append("\n");
    sb.append("    boltzMempoolSpaceUrl: ").append(toIndentedString(boltzMempoolSpaceUrl)).append("\n");
    sb.append("    boltzMempoolSpaceUrlWs: ").append(toIndentedString(boltzMempoolSpaceUrlWs)).append("\n");
    sb.append("    lntipsApiEndpoint: ").append(toIndentedString(lntipsApiEndpoint)).append("\n");
    sb.append("    lntipsApiKey: ").append(toIndentedString(lntipsApiKey)).append("\n");
    sb.append("    lntipsAdminKey: ").append(toIndentedString(lntipsAdminKey)).append("\n");
    sb.append("    lntipsInvoiceKey: ").append(toIndentedString(lntipsInvoiceKey)).append("\n");
    sb.append("    sparkUrl: ").append(toIndentedString(sparkUrl)).append("\n");
    sb.append("    sparkToken: ").append(toIndentedString(sparkToken)).append("\n");
    sb.append("    opennodeApiEndpoint: ").append(toIndentedString(opennodeApiEndpoint)).append("\n");
    sb.append("    opennodeKey: ").append(toIndentedString(opennodeKey)).append("\n");
    sb.append("    opennodeAdminKey: ").append(toIndentedString(opennodeAdminKey)).append("\n");
    sb.append("    opennodeInvoiceKey: ").append(toIndentedString(opennodeInvoiceKey)).append("\n");
    sb.append("    lnpayApiEndpoint: ").append(toIndentedString(lnpayApiEndpoint)).append("\n");
    sb.append("    lnpayApiKey: ").append(toIndentedString(lnpayApiKey)).append("\n");
    sb.append("    lnpayWalletKey: ").append(toIndentedString(lnpayWalletKey)).append("\n");
    sb.append("    lnpayAdminKey: ").append(toIndentedString(lnpayAdminKey)).append("\n");
    sb.append("    lndGrpcEndpoint: ").append(toIndentedString(lndGrpcEndpoint)).append("\n");
    sb.append("    lndGrpcCert: ").append(toIndentedString(lndGrpcCert)).append("\n");
    sb.append("    lndGrpcPort: ").append(toIndentedString(lndGrpcPort)).append("\n");
    sb.append("    lndGrpcAdminMacaroon: ").append(toIndentedString(lndGrpcAdminMacaroon)).append("\n");
    sb.append("    lndGrpcInvoiceMacaroon: ").append(toIndentedString(lndGrpcInvoiceMacaroon)).append("\n");
    sb.append("    lndGrpcMacaroon: ").append(toIndentedString(lndGrpcMacaroon)).append("\n");
    sb.append("    lndGrpcMacaroonEncrypted: ").append(toIndentedString(lndGrpcMacaroonEncrypted)).append("\n");
    sb.append("    lndRestEndpoint: ").append(toIndentedString(lndRestEndpoint)).append("\n");
    sb.append("    lndRestCert: ").append(toIndentedString(lndRestCert)).append("\n");
    sb.append("    lndRestMacaroon: ").append(toIndentedString(lndRestMacaroon)).append("\n");
    sb.append("    lndRestMacaroonEncrypted: ").append(toIndentedString(lndRestMacaroonEncrypted)).append("\n");
    sb.append("    lndCert: ").append(toIndentedString(lndCert)).append("\n");
    sb.append("    lndAdminMacaroon: ").append(toIndentedString(lndAdminMacaroon)).append("\n");
    sb.append("    lndInvoiceMacaroon: ").append(toIndentedString(lndInvoiceMacaroon)).append("\n");
    sb.append("    lndRestAdminMacaroon: ").append(toIndentedString(lndRestAdminMacaroon)).append("\n");
    sb.append("    lndRestInvoiceMacaroon: ").append(toIndentedString(lndRestInvoiceMacaroon)).append("\n");
    sb.append("    eclairUrl: ").append(toIndentedString(eclairUrl)).append("\n");
    sb.append("    eclairPass: ").append(toIndentedString(eclairPass)).append("\n");
    sb.append("    corelightningRpc: ").append(toIndentedString(corelightningRpc)).append("\n");
    sb.append("    clightningRpc: ").append(toIndentedString(clightningRpc)).append("\n");
    sb.append("    clicheEndpoint: ").append(toIndentedString(clicheEndpoint)).append("\n");
    sb.append("    lnbitsEndpoint: ").append(toIndentedString(lnbitsEndpoint)).append("\n");
    sb.append("    lnbitsKey: ").append(toIndentedString(lnbitsKey)).append("\n");
    sb.append("    lnbitsAdminKey: ").append(toIndentedString(lnbitsAdminKey)).append("\n");
    sb.append("    lnbitsInvoiceKey: ").append(toIndentedString(lnbitsInvoiceKey)).append("\n");
    sb.append("    fakeWalletSecret: ").append(toIndentedString(fakeWalletSecret)).append("\n");
    sb.append("    lnbitsBackendWalletClass: ").append(toIndentedString(lnbitsBackendWalletClass)).append("\n");
    sb.append("    lnbitsRateLimitNo: ").append(toIndentedString(lnbitsRateLimitNo)).append("\n");
    sb.append("    lnbitsRateLimitUnit: ").append(toIndentedString(lnbitsRateLimitUnit)).append("\n");
    sb.append("    lnbitsAllowedIps: ").append(toIndentedString(lnbitsAllowedIps)).append("\n");
    sb.append("    lnbitsBlockedIps: ").append(toIndentedString(lnbitsBlockedIps)).append("\n");
    sb.append("    lnbitsNotifications: ").append(toIndentedString(lnbitsNotifications)).append("\n");
    sb.append("    lnbitsKillswitch: ").append(toIndentedString(lnbitsKillswitch)).append("\n");
    sb.append("    lnbitsKillswitchInterval: ").append(toIndentedString(lnbitsKillswitchInterval)).append("\n");
    sb.append("    lnbitsWatchdog: ").append(toIndentedString(lnbitsWatchdog)).append("\n");
    sb.append("    lnbitsWatchdogInterval: ").append(toIndentedString(lnbitsWatchdogInterval)).append("\n");
    sb.append("    lnbitsWatchdogDelta: ").append(toIndentedString(lnbitsWatchdogDelta)).append("\n");
    sb.append("    lnbitsStatusManifest: ").append(toIndentedString(lnbitsStatusManifest)).append("\n");
    sb.append("    lnbitsBaseurl: ").append(toIndentedString(lnbitsBaseurl)).append("\n");
    sb.append("    lnbitsReserveFeeMin: ").append(toIndentedString(lnbitsReserveFeeMin)).append("\n");
    sb.append("    lnbitsReserveFeePercent: ").append(toIndentedString(lnbitsReserveFeePercent)).append("\n");
    sb.append("    lnbitsServiceFee: ").append(toIndentedString(lnbitsServiceFee)).append("\n");
    sb.append("    lnbitsHideApi: ").append(toIndentedString(lnbitsHideApi)).append("\n");
    sb.append("    lnbitsDenomination: ").append(toIndentedString(lnbitsDenomination)).append("\n");
    sb.append("    lnbitsSiteTitle: ").append(toIndentedString(lnbitsSiteTitle)).append("\n");
    sb.append("    lnbitsSiteTagline: ").append(toIndentedString(lnbitsSiteTagline)).append("\n");
    sb.append("    lnbitsSiteDescription: ").append(toIndentedString(lnbitsSiteDescription)).append("\n");
    sb.append("    lnbitsDefaultWalletName: ").append(toIndentedString(lnbitsDefaultWalletName)).append("\n");
    sb.append("    lnbitsThemeOptions: ").append(toIndentedString(lnbitsThemeOptions)).append("\n");
    sb.append("    lnbitsCustomLogo: ").append(toIndentedString(lnbitsCustomLogo)).append("\n");
    sb.append("    lnbitsAdSpaceTitle: ").append(toIndentedString(lnbitsAdSpaceTitle)).append("\n");
    sb.append("    lnbitsAdSpace: ").append(toIndentedString(lnbitsAdSpace)).append("\n");
    sb.append("    lnbitsAdSpaceEnabled: ").append(toIndentedString(lnbitsAdSpaceEnabled)).append("\n");
    sb.append("    lnbitsAllowedCurrencies: ").append(toIndentedString(lnbitsAllowedCurrencies)).append("\n");
    sb.append("    lnbitsAdminExtensions: ").append(toIndentedString(lnbitsAdminExtensions)).append("\n");
    sb.append("    lnbitsExtensionsManifests: ").append(toIndentedString(lnbitsExtensionsManifests)).append("\n");
    sb.append("    lnbitsAdminUsers: ").append(toIndentedString(lnbitsAdminUsers)).append("\n");
    sb.append("    lnbitsAllowedUsers: ").append(toIndentedString(lnbitsAllowedUsers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("lightning_invoice_expiry");
    openapiFields.add("boltz_network");
    openapiFields.add("boltz_url");
    openapiFields.add("boltz_mempool_space_url");
    openapiFields.add("boltz_mempool_space_url_ws");
    openapiFields.add("lntips_api_endpoint");
    openapiFields.add("lntips_api_key");
    openapiFields.add("lntips_admin_key");
    openapiFields.add("lntips_invoice_key");
    openapiFields.add("spark_url");
    openapiFields.add("spark_token");
    openapiFields.add("opennode_api_endpoint");
    openapiFields.add("opennode_key");
    openapiFields.add("opennode_admin_key");
    openapiFields.add("opennode_invoice_key");
    openapiFields.add("lnpay_api_endpoint");
    openapiFields.add("lnpay_api_key");
    openapiFields.add("lnpay_wallet_key");
    openapiFields.add("lnpay_admin_key");
    openapiFields.add("lnd_grpc_endpoint");
    openapiFields.add("lnd_grpc_cert");
    openapiFields.add("lnd_grpc_port");
    openapiFields.add("lnd_grpc_admin_macaroon");
    openapiFields.add("lnd_grpc_invoice_macaroon");
    openapiFields.add("lnd_grpc_macaroon");
    openapiFields.add("lnd_grpc_macaroon_encrypted");
    openapiFields.add("lnd_rest_endpoint");
    openapiFields.add("lnd_rest_cert");
    openapiFields.add("lnd_rest_macaroon");
    openapiFields.add("lnd_rest_macaroon_encrypted");
    openapiFields.add("lnd_cert");
    openapiFields.add("lnd_admin_macaroon");
    openapiFields.add("lnd_invoice_macaroon");
    openapiFields.add("lnd_rest_admin_macaroon");
    openapiFields.add("lnd_rest_invoice_macaroon");
    openapiFields.add("eclair_url");
    openapiFields.add("eclair_pass");
    openapiFields.add("corelightning_rpc");
    openapiFields.add("clightning_rpc");
    openapiFields.add("cliche_endpoint");
    openapiFields.add("lnbits_endpoint");
    openapiFields.add("lnbits_key");
    openapiFields.add("lnbits_admin_key");
    openapiFields.add("lnbits_invoice_key");
    openapiFields.add("fake_wallet_secret");
    openapiFields.add("lnbits_backend_wallet_class");
    openapiFields.add("lnbits_rate_limit_no");
    openapiFields.add("lnbits_rate_limit_unit");
    openapiFields.add("lnbits_allowed_ips");
    openapiFields.add("lnbits_blocked_ips");
    openapiFields.add("lnbits_notifications");
    openapiFields.add("lnbits_killswitch");
    openapiFields.add("lnbits_killswitch_interval");
    openapiFields.add("lnbits_watchdog");
    openapiFields.add("lnbits_watchdog_interval");
    openapiFields.add("lnbits_watchdog_delta");
    openapiFields.add("lnbits_status_manifest");
    openapiFields.add("lnbits_baseurl");
    openapiFields.add("lnbits_reserve_fee_min");
    openapiFields.add("lnbits_reserve_fee_percent");
    openapiFields.add("lnbits_service_fee");
    openapiFields.add("lnbits_hide_api");
    openapiFields.add("lnbits_denomination");
    openapiFields.add("lnbits_site_title");
    openapiFields.add("lnbits_site_tagline");
    openapiFields.add("lnbits_site_description");
    openapiFields.add("lnbits_default_wallet_name");
    openapiFields.add("lnbits_theme_options");
    openapiFields.add("lnbits_custom_logo");
    openapiFields.add("lnbits_ad_space_title");
    openapiFields.add("lnbits_ad_space");
    openapiFields.add("lnbits_ad_space_enabled");
    openapiFields.add("lnbits_allowed_currencies");
    openapiFields.add("lnbits_admin_extensions");
    openapiFields.add("lnbits_extensions_manifests");
    openapiFields.add("lnbits_admin_users");
    openapiFields.add("lnbits_allowed_users");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to EditableSettings
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!EditableSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EditableSettings is not found in the empty JSON string", EditableSettings.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!EditableSettings.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EditableSettings` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("boltz_network") != null && !jsonObj.get("boltz_network").isJsonNull()) && !jsonObj.get("boltz_network").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `boltz_network` to be a primitive type in the JSON string but got `%s`", jsonObj.get("boltz_network").toString()));
      }
      if ((jsonObj.get("boltz_url") != null && !jsonObj.get("boltz_url").isJsonNull()) && !jsonObj.get("boltz_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `boltz_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("boltz_url").toString()));
      }
      if ((jsonObj.get("boltz_mempool_space_url") != null && !jsonObj.get("boltz_mempool_space_url").isJsonNull()) && !jsonObj.get("boltz_mempool_space_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `boltz_mempool_space_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("boltz_mempool_space_url").toString()));
      }
      if ((jsonObj.get("boltz_mempool_space_url_ws") != null && !jsonObj.get("boltz_mempool_space_url_ws").isJsonNull()) && !jsonObj.get("boltz_mempool_space_url_ws").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `boltz_mempool_space_url_ws` to be a primitive type in the JSON string but got `%s`", jsonObj.get("boltz_mempool_space_url_ws").toString()));
      }
      if ((jsonObj.get("lntips_api_endpoint") != null && !jsonObj.get("lntips_api_endpoint").isJsonNull()) && !jsonObj.get("lntips_api_endpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lntips_api_endpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lntips_api_endpoint").toString()));
      }
      if ((jsonObj.get("lntips_api_key") != null && !jsonObj.get("lntips_api_key").isJsonNull()) && !jsonObj.get("lntips_api_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lntips_api_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lntips_api_key").toString()));
      }
      if ((jsonObj.get("lntips_admin_key") != null && !jsonObj.get("lntips_admin_key").isJsonNull()) && !jsonObj.get("lntips_admin_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lntips_admin_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lntips_admin_key").toString()));
      }
      if ((jsonObj.get("lntips_invoice_key") != null && !jsonObj.get("lntips_invoice_key").isJsonNull()) && !jsonObj.get("lntips_invoice_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lntips_invoice_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lntips_invoice_key").toString()));
      }
      if ((jsonObj.get("spark_url") != null && !jsonObj.get("spark_url").isJsonNull()) && !jsonObj.get("spark_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `spark_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("spark_url").toString()));
      }
      if ((jsonObj.get("spark_token") != null && !jsonObj.get("spark_token").isJsonNull()) && !jsonObj.get("spark_token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `spark_token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("spark_token").toString()));
      }
      if ((jsonObj.get("opennode_api_endpoint") != null && !jsonObj.get("opennode_api_endpoint").isJsonNull()) && !jsonObj.get("opennode_api_endpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `opennode_api_endpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("opennode_api_endpoint").toString()));
      }
      if ((jsonObj.get("opennode_key") != null && !jsonObj.get("opennode_key").isJsonNull()) && !jsonObj.get("opennode_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `opennode_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("opennode_key").toString()));
      }
      if ((jsonObj.get("opennode_admin_key") != null && !jsonObj.get("opennode_admin_key").isJsonNull()) && !jsonObj.get("opennode_admin_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `opennode_admin_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("opennode_admin_key").toString()));
      }
      if ((jsonObj.get("opennode_invoice_key") != null && !jsonObj.get("opennode_invoice_key").isJsonNull()) && !jsonObj.get("opennode_invoice_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `opennode_invoice_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("opennode_invoice_key").toString()));
      }
      if ((jsonObj.get("lnpay_api_endpoint") != null && !jsonObj.get("lnpay_api_endpoint").isJsonNull()) && !jsonObj.get("lnpay_api_endpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnpay_api_endpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnpay_api_endpoint").toString()));
      }
      if ((jsonObj.get("lnpay_api_key") != null && !jsonObj.get("lnpay_api_key").isJsonNull()) && !jsonObj.get("lnpay_api_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnpay_api_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnpay_api_key").toString()));
      }
      if ((jsonObj.get("lnpay_wallet_key") != null && !jsonObj.get("lnpay_wallet_key").isJsonNull()) && !jsonObj.get("lnpay_wallet_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnpay_wallet_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnpay_wallet_key").toString()));
      }
      if ((jsonObj.get("lnpay_admin_key") != null && !jsonObj.get("lnpay_admin_key").isJsonNull()) && !jsonObj.get("lnpay_admin_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnpay_admin_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnpay_admin_key").toString()));
      }
      if ((jsonObj.get("lnd_grpc_endpoint") != null && !jsonObj.get("lnd_grpc_endpoint").isJsonNull()) && !jsonObj.get("lnd_grpc_endpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnd_grpc_endpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnd_grpc_endpoint").toString()));
      }
      if ((jsonObj.get("lnd_grpc_cert") != null && !jsonObj.get("lnd_grpc_cert").isJsonNull()) && !jsonObj.get("lnd_grpc_cert").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnd_grpc_cert` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnd_grpc_cert").toString()));
      }
      if ((jsonObj.get("lnd_grpc_admin_macaroon") != null && !jsonObj.get("lnd_grpc_admin_macaroon").isJsonNull()) && !jsonObj.get("lnd_grpc_admin_macaroon").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnd_grpc_admin_macaroon` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnd_grpc_admin_macaroon").toString()));
      }
      if ((jsonObj.get("lnd_grpc_invoice_macaroon") != null && !jsonObj.get("lnd_grpc_invoice_macaroon").isJsonNull()) && !jsonObj.get("lnd_grpc_invoice_macaroon").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnd_grpc_invoice_macaroon` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnd_grpc_invoice_macaroon").toString()));
      }
      if ((jsonObj.get("lnd_grpc_macaroon") != null && !jsonObj.get("lnd_grpc_macaroon").isJsonNull()) && !jsonObj.get("lnd_grpc_macaroon").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnd_grpc_macaroon` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnd_grpc_macaroon").toString()));
      }
      if ((jsonObj.get("lnd_grpc_macaroon_encrypted") != null && !jsonObj.get("lnd_grpc_macaroon_encrypted").isJsonNull()) && !jsonObj.get("lnd_grpc_macaroon_encrypted").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnd_grpc_macaroon_encrypted` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnd_grpc_macaroon_encrypted").toString()));
      }
      if ((jsonObj.get("lnd_rest_endpoint") != null && !jsonObj.get("lnd_rest_endpoint").isJsonNull()) && !jsonObj.get("lnd_rest_endpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnd_rest_endpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnd_rest_endpoint").toString()));
      }
      if ((jsonObj.get("lnd_rest_cert") != null && !jsonObj.get("lnd_rest_cert").isJsonNull()) && !jsonObj.get("lnd_rest_cert").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnd_rest_cert` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnd_rest_cert").toString()));
      }
      if ((jsonObj.get("lnd_rest_macaroon") != null && !jsonObj.get("lnd_rest_macaroon").isJsonNull()) && !jsonObj.get("lnd_rest_macaroon").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnd_rest_macaroon` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnd_rest_macaroon").toString()));
      }
      if ((jsonObj.get("lnd_rest_macaroon_encrypted") != null && !jsonObj.get("lnd_rest_macaroon_encrypted").isJsonNull()) && !jsonObj.get("lnd_rest_macaroon_encrypted").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnd_rest_macaroon_encrypted` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnd_rest_macaroon_encrypted").toString()));
      }
      if ((jsonObj.get("lnd_cert") != null && !jsonObj.get("lnd_cert").isJsonNull()) && !jsonObj.get("lnd_cert").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnd_cert` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnd_cert").toString()));
      }
      if ((jsonObj.get("lnd_admin_macaroon") != null && !jsonObj.get("lnd_admin_macaroon").isJsonNull()) && !jsonObj.get("lnd_admin_macaroon").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnd_admin_macaroon` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnd_admin_macaroon").toString()));
      }
      if ((jsonObj.get("lnd_invoice_macaroon") != null && !jsonObj.get("lnd_invoice_macaroon").isJsonNull()) && !jsonObj.get("lnd_invoice_macaroon").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnd_invoice_macaroon` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnd_invoice_macaroon").toString()));
      }
      if ((jsonObj.get("lnd_rest_admin_macaroon") != null && !jsonObj.get("lnd_rest_admin_macaroon").isJsonNull()) && !jsonObj.get("lnd_rest_admin_macaroon").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnd_rest_admin_macaroon` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnd_rest_admin_macaroon").toString()));
      }
      if ((jsonObj.get("lnd_rest_invoice_macaroon") != null && !jsonObj.get("lnd_rest_invoice_macaroon").isJsonNull()) && !jsonObj.get("lnd_rest_invoice_macaroon").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnd_rest_invoice_macaroon` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnd_rest_invoice_macaroon").toString()));
      }
      if ((jsonObj.get("eclair_url") != null && !jsonObj.get("eclair_url").isJsonNull()) && !jsonObj.get("eclair_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `eclair_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("eclair_url").toString()));
      }
      if ((jsonObj.get("eclair_pass") != null && !jsonObj.get("eclair_pass").isJsonNull()) && !jsonObj.get("eclair_pass").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `eclair_pass` to be a primitive type in the JSON string but got `%s`", jsonObj.get("eclair_pass").toString()));
      }
      if ((jsonObj.get("corelightning_rpc") != null && !jsonObj.get("corelightning_rpc").isJsonNull()) && !jsonObj.get("corelightning_rpc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `corelightning_rpc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("corelightning_rpc").toString()));
      }
      if ((jsonObj.get("clightning_rpc") != null && !jsonObj.get("clightning_rpc").isJsonNull()) && !jsonObj.get("clightning_rpc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clightning_rpc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clightning_rpc").toString()));
      }
      if ((jsonObj.get("cliche_endpoint") != null && !jsonObj.get("cliche_endpoint").isJsonNull()) && !jsonObj.get("cliche_endpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cliche_endpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cliche_endpoint").toString()));
      }
      if ((jsonObj.get("lnbits_endpoint") != null && !jsonObj.get("lnbits_endpoint").isJsonNull()) && !jsonObj.get("lnbits_endpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_endpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_endpoint").toString()));
      }
      if ((jsonObj.get("lnbits_key") != null && !jsonObj.get("lnbits_key").isJsonNull()) && !jsonObj.get("lnbits_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_key").toString()));
      }
      if ((jsonObj.get("lnbits_admin_key") != null && !jsonObj.get("lnbits_admin_key").isJsonNull()) && !jsonObj.get("lnbits_admin_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_admin_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_admin_key").toString()));
      }
      if ((jsonObj.get("lnbits_invoice_key") != null && !jsonObj.get("lnbits_invoice_key").isJsonNull()) && !jsonObj.get("lnbits_invoice_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_invoice_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_invoice_key").toString()));
      }
      if ((jsonObj.get("fake_wallet_secret") != null && !jsonObj.get("fake_wallet_secret").isJsonNull()) && !jsonObj.get("fake_wallet_secret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fake_wallet_secret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fake_wallet_secret").toString()));
      }
      if ((jsonObj.get("lnbits_backend_wallet_class") != null && !jsonObj.get("lnbits_backend_wallet_class").isJsonNull()) && !jsonObj.get("lnbits_backend_wallet_class").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_backend_wallet_class` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_backend_wallet_class").toString()));
      }
      if ((jsonObj.get("lnbits_rate_limit_no") != null && !jsonObj.get("lnbits_rate_limit_no").isJsonNull()) && !jsonObj.get("lnbits_rate_limit_no").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_rate_limit_no` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_rate_limit_no").toString()));
      }
      if ((jsonObj.get("lnbits_rate_limit_unit") != null && !jsonObj.get("lnbits_rate_limit_unit").isJsonNull()) && !jsonObj.get("lnbits_rate_limit_unit").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_rate_limit_unit` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_rate_limit_unit").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("lnbits_allowed_ips") != null && !jsonObj.get("lnbits_allowed_ips").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_allowed_ips` to be an array in the JSON string but got `%s`", jsonObj.get("lnbits_allowed_ips").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("lnbits_blocked_ips") != null && !jsonObj.get("lnbits_blocked_ips").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_blocked_ips` to be an array in the JSON string but got `%s`", jsonObj.get("lnbits_blocked_ips").toString()));
      }
      if ((jsonObj.get("lnbits_status_manifest") != null && !jsonObj.get("lnbits_status_manifest").isJsonNull()) && !jsonObj.get("lnbits_status_manifest").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_status_manifest` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_status_manifest").toString()));
      }
      if ((jsonObj.get("lnbits_baseurl") != null && !jsonObj.get("lnbits_baseurl").isJsonNull()) && !jsonObj.get("lnbits_baseurl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_baseurl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_baseurl").toString()));
      }
      if ((jsonObj.get("lnbits_denomination") != null && !jsonObj.get("lnbits_denomination").isJsonNull()) && !jsonObj.get("lnbits_denomination").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_denomination` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_denomination").toString()));
      }
      if ((jsonObj.get("lnbits_site_title") != null && !jsonObj.get("lnbits_site_title").isJsonNull()) && !jsonObj.get("lnbits_site_title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_site_title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_site_title").toString()));
      }
      if ((jsonObj.get("lnbits_site_tagline") != null && !jsonObj.get("lnbits_site_tagline").isJsonNull()) && !jsonObj.get("lnbits_site_tagline").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_site_tagline` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_site_tagline").toString()));
      }
      if ((jsonObj.get("lnbits_site_description") != null && !jsonObj.get("lnbits_site_description").isJsonNull()) && !jsonObj.get("lnbits_site_description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_site_description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_site_description").toString()));
      }
      if ((jsonObj.get("lnbits_default_wallet_name") != null && !jsonObj.get("lnbits_default_wallet_name").isJsonNull()) && !jsonObj.get("lnbits_default_wallet_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_default_wallet_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_default_wallet_name").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("lnbits_theme_options") != null && !jsonObj.get("lnbits_theme_options").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_theme_options` to be an array in the JSON string but got `%s`", jsonObj.get("lnbits_theme_options").toString()));
      }
      if ((jsonObj.get("lnbits_custom_logo") != null && !jsonObj.get("lnbits_custom_logo").isJsonNull()) && !jsonObj.get("lnbits_custom_logo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_custom_logo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_custom_logo").toString()));
      }
      if ((jsonObj.get("lnbits_ad_space_title") != null && !jsonObj.get("lnbits_ad_space_title").isJsonNull()) && !jsonObj.get("lnbits_ad_space_title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_ad_space_title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_ad_space_title").toString()));
      }
      if ((jsonObj.get("lnbits_ad_space") != null && !jsonObj.get("lnbits_ad_space").isJsonNull()) && !jsonObj.get("lnbits_ad_space").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_ad_space` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lnbits_ad_space").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("lnbits_allowed_currencies") != null && !jsonObj.get("lnbits_allowed_currencies").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_allowed_currencies` to be an array in the JSON string but got `%s`", jsonObj.get("lnbits_allowed_currencies").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("lnbits_admin_extensions") != null && !jsonObj.get("lnbits_admin_extensions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_admin_extensions` to be an array in the JSON string but got `%s`", jsonObj.get("lnbits_admin_extensions").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("lnbits_extensions_manifests") != null && !jsonObj.get("lnbits_extensions_manifests").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_extensions_manifests` to be an array in the JSON string but got `%s`", jsonObj.get("lnbits_extensions_manifests").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("lnbits_admin_users") != null && !jsonObj.get("lnbits_admin_users").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_admin_users` to be an array in the JSON string but got `%s`", jsonObj.get("lnbits_admin_users").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("lnbits_allowed_users") != null && !jsonObj.get("lnbits_allowed_users").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `lnbits_allowed_users` to be an array in the JSON string but got `%s`", jsonObj.get("lnbits_allowed_users").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EditableSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EditableSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EditableSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EditableSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<EditableSettings>() {
           @Override
           public void write(JsonWriter out, EditableSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EditableSettings read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EditableSettings given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EditableSettings
  * @throws IOException if the JSON string is invalid with respect to EditableSettings
  */
  public static EditableSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EditableSettings.class);
  }

 /**
  * Convert an instance of EditableSettings to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

